/*
 * This file is generated by jOOQ.
 */
package PlatniPrometDB.tables;


import PlatniPrometDB.Keys;
import PlatniPrometDB.Public;
import PlatniPrometDB.tables.records.ExchangeCashDenominationRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function14;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row14;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExchangeCashDenomination extends TableImpl<ExchangeCashDenominationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.exchange_cash_denomination</code>
     */
    public static final ExchangeCashDenomination EXCHANGE_CASH_DENOMINATION = new ExchangeCashDenomination();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ExchangeCashDenominationRecord> getRecordType() {
        return ExchangeCashDenominationRecord.class;
    }

    /**
     * The column
     * <code>public.exchange_cash_denomination.exchange_cash_denomination_id</code>.
     */
    public final TableField<ExchangeCashDenominationRecord, Long> EXCHANGE_CASH_DENOMINATION_ID = createField(DSL.name("exchange_cash_denomination_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column
     * <code>public.exchange_cash_denomination.exchange_job_id</code>.
     */
    public final TableField<ExchangeCashDenominationRecord, Long> EXCHANGE_JOB_ID = createField(DSL.name("exchange_job_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.exchange_cash_denomination.x1</code>.
     */
    public final TableField<ExchangeCashDenominationRecord, Integer> X1 = createField(DSL.name("x1"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.exchange_cash_denomination.x2</code>.
     */
    public final TableField<ExchangeCashDenominationRecord, Integer> X2 = createField(DSL.name("x2"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.exchange_cash_denomination.x5</code>.
     */
    public final TableField<ExchangeCashDenominationRecord, Integer> X5 = createField(DSL.name("x5"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.exchange_cash_denomination.x10</code>.
     */
    public final TableField<ExchangeCashDenominationRecord, Integer> X10 = createField(DSL.name("x10"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.exchange_cash_denomination.x20</code>.
     */
    public final TableField<ExchangeCashDenominationRecord, Integer> X20 = createField(DSL.name("x20"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.exchange_cash_denomination.x50</code>.
     */
    public final TableField<ExchangeCashDenominationRecord, Integer> X50 = createField(DSL.name("x50"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.exchange_cash_denomination.x100</code>.
     */
    public final TableField<ExchangeCashDenominationRecord, Integer> X100 = createField(DSL.name("x100"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.exchange_cash_denomination.x200</code>.
     */
    public final TableField<ExchangeCashDenominationRecord, Integer> X200 = createField(DSL.name("x200"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.exchange_cash_denomination.x500</code>.
     */
    public final TableField<ExchangeCashDenominationRecord, Integer> X500 = createField(DSL.name("x500"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.exchange_cash_denomination.x1000</code>.
     */
    public final TableField<ExchangeCashDenominationRecord, Integer> X1000 = createField(DSL.name("x1000"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.exchange_cash_denomination.x2000</code>.
     */
    public final TableField<ExchangeCashDenominationRecord, Integer> X2000 = createField(DSL.name("x2000"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.exchange_cash_denomination.x5000</code>.
     */
    public final TableField<ExchangeCashDenominationRecord, Integer> X5000 = createField(DSL.name("x5000"), SQLDataType.INTEGER, this, "");

    private ExchangeCashDenomination(Name alias, Table<ExchangeCashDenominationRecord> aliased) {
        this(alias, aliased, null);
    }

    private ExchangeCashDenomination(Name alias, Table<ExchangeCashDenominationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.exchange_cash_denomination</code> table
     * reference
     */
    public ExchangeCashDenomination(String alias) {
        this(DSL.name(alias), EXCHANGE_CASH_DENOMINATION);
    }

    /**
     * Create an aliased <code>public.exchange_cash_denomination</code> table
     * reference
     */
    public ExchangeCashDenomination(Name alias) {
        this(alias, EXCHANGE_CASH_DENOMINATION);
    }

    /**
     * Create a <code>public.exchange_cash_denomination</code> table reference
     */
    public ExchangeCashDenomination() {
        this(DSL.name("exchange_cash_denomination"), null);
    }

    public <O extends Record> ExchangeCashDenomination(Table<O> child, ForeignKey<O, ExchangeCashDenominationRecord> key) {
        super(child, key, EXCHANGE_CASH_DENOMINATION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ExchangeCashDenominationRecord, Long> getIdentity() {
        return (Identity<ExchangeCashDenominationRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ExchangeCashDenominationRecord> getPrimaryKey() {
        return Keys.EXCHANGE_CASH_DENOMINATION_PKEY;
    }

    @Override
    public ExchangeCashDenomination as(String alias) {
        return new ExchangeCashDenomination(DSL.name(alias), this);
    }

    @Override
    public ExchangeCashDenomination as(Name alias) {
        return new ExchangeCashDenomination(alias, this);
    }

    @Override
    public ExchangeCashDenomination as(Table<?> alias) {
        return new ExchangeCashDenomination(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ExchangeCashDenomination rename(String name) {
        return new ExchangeCashDenomination(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ExchangeCashDenomination rename(Name name) {
        return new ExchangeCashDenomination(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ExchangeCashDenomination rename(Table<?> name) {
        return new ExchangeCashDenomination(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row14 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row14<Long, Long, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function14<? super Long, ? super Long, ? super Integer, ? super Integer, ? super Integer, ? super Integer, ? super Integer, ? super Integer, ? super Integer, ? super Integer, ? super Integer, ? super Integer, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function14<? super Long, ? super Long, ? super Integer, ? super Integer, ? super Integer, ? super Integer, ? super Integer, ? super Integer, ? super Integer, ? super Integer, ? super Integer, ? super Integer, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
