/*
 * This file is generated by jOOQ.
 */
package PlatniPrometDB.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BalanceEntry implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long balanceEntryId;
    private Integer entrySide;
    private Long cashRegisterId;
    private Long entryTypeId;
    private String currencyCode;
    private BigDecimal amount;
    private Long jobTypeId;
    private Long jobId;
    private Long workPlaceId;
    private Long userId;
    private OffsetDateTime timestampOfCreation;
    private LocalDate dateOfCreation;
    private LocalTime timeOfCreation;

    public BalanceEntry() {}

    public BalanceEntry(BalanceEntry value) {
        this.balanceEntryId = value.balanceEntryId;
        this.entrySide = value.entrySide;
        this.cashRegisterId = value.cashRegisterId;
        this.entryTypeId = value.entryTypeId;
        this.currencyCode = value.currencyCode;
        this.amount = value.amount;
        this.jobTypeId = value.jobTypeId;
        this.jobId = value.jobId;
        this.workPlaceId = value.workPlaceId;
        this.userId = value.userId;
        this.timestampOfCreation = value.timestampOfCreation;
        this.dateOfCreation = value.dateOfCreation;
        this.timeOfCreation = value.timeOfCreation;
    }

    public BalanceEntry(
        Long balanceEntryId,
        Integer entrySide,
        Long cashRegisterId,
        Long entryTypeId,
        String currencyCode,
        BigDecimal amount,
        Long jobTypeId,
        Long jobId,
        Long workPlaceId,
        Long userId,
        OffsetDateTime timestampOfCreation,
        LocalDate dateOfCreation,
        LocalTime timeOfCreation
    ) {
        this.balanceEntryId = balanceEntryId;
        this.entrySide = entrySide;
        this.cashRegisterId = cashRegisterId;
        this.entryTypeId = entryTypeId;
        this.currencyCode = currencyCode;
        this.amount = amount;
        this.jobTypeId = jobTypeId;
        this.jobId = jobId;
        this.workPlaceId = workPlaceId;
        this.userId = userId;
        this.timestampOfCreation = timestampOfCreation;
        this.dateOfCreation = dateOfCreation;
        this.timeOfCreation = timeOfCreation;
    }

    /**
     * Getter for <code>public.balance_entry.balance_entry_id</code>.
     */
    public Long getBalanceEntryId() {
        return this.balanceEntryId;
    }

    /**
     * Setter for <code>public.balance_entry.balance_entry_id</code>.
     */
    public void setBalanceEntryId(Long balanceEntryId) {
        this.balanceEntryId = balanceEntryId;
    }

    /**
     * Getter for <code>public.balance_entry.entry_side</code>. 1 - In, 2 - Out
     */
    public Integer getEntrySide() {
        return this.entrySide;
    }

    /**
     * Setter for <code>public.balance_entry.entry_side</code>. 1 - In, 2 - Out
     */
    public void setEntrySide(Integer entrySide) {
        this.entrySide = entrySide;
    }

    /**
     * Getter for <code>public.balance_entry.cash_register_id</code>.
     */
    public Long getCashRegisterId() {
        return this.cashRegisterId;
    }

    /**
     * Setter for <code>public.balance_entry.cash_register_id</code>.
     */
    public void setCashRegisterId(Long cashRegisterId) {
        this.cashRegisterId = cashRegisterId;
    }

    /**
     * Getter for <code>public.balance_entry.entry_type_id</code>. 1 - Exchange,
     * 2 - Transfer
     */
    public Long getEntryTypeId() {
        return this.entryTypeId;
    }

    /**
     * Setter for <code>public.balance_entry.entry_type_id</code>. 1 - Exchange,
     * 2 - Transfer
     */
    public void setEntryTypeId(Long entryTypeId) {
        this.entryTypeId = entryTypeId;
    }

    /**
     * Getter for <code>public.balance_entry.currency_code</code>.
     */
    public String getCurrencyCode() {
        return this.currencyCode;
    }

    /**
     * Setter for <code>public.balance_entry.currency_code</code>.
     */
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    /**
     * Getter for <code>public.balance_entry.amount</code>.
     */
    public BigDecimal getAmount() {
        return this.amount;
    }

    /**
     * Setter for <code>public.balance_entry.amount</code>.
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * Getter for <code>public.balance_entry.job_type_id</code>.
     */
    public Long getJobTypeId() {
        return this.jobTypeId;
    }

    /**
     * Setter for <code>public.balance_entry.job_type_id</code>.
     */
    public void setJobTypeId(Long jobTypeId) {
        this.jobTypeId = jobTypeId;
    }

    /**
     * Getter for <code>public.balance_entry.job_id</code>.
     */
    public Long getJobId() {
        return this.jobId;
    }

    /**
     * Setter for <code>public.balance_entry.job_id</code>.
     */
    public void setJobId(Long jobId) {
        this.jobId = jobId;
    }

    /**
     * Getter for <code>public.balance_entry.work_place_id</code>.
     */
    public Long getWorkPlaceId() {
        return this.workPlaceId;
    }

    /**
     * Setter for <code>public.balance_entry.work_place_id</code>.
     */
    public void setWorkPlaceId(Long workPlaceId) {
        this.workPlaceId = workPlaceId;
    }

    /**
     * Getter for <code>public.balance_entry.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.balance_entry.user_id</code>.
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>public.balance_entry.timestamp_of_creation</code>.
     */
    public OffsetDateTime getTimestampOfCreation() {
        return this.timestampOfCreation;
    }

    /**
     * Setter for <code>public.balance_entry.timestamp_of_creation</code>.
     */
    public void setTimestampOfCreation(OffsetDateTime timestampOfCreation) {
        this.timestampOfCreation = timestampOfCreation;
    }

    /**
     * Getter for <code>public.balance_entry.date_of_creation</code>.
     */
    public LocalDate getDateOfCreation() {
        return this.dateOfCreation;
    }

    /**
     * Setter for <code>public.balance_entry.date_of_creation</code>.
     */
    public void setDateOfCreation(LocalDate dateOfCreation) {
        this.dateOfCreation = dateOfCreation;
    }

    /**
     * Getter for <code>public.balance_entry.time_of_creation</code>.
     */
    public LocalTime getTimeOfCreation() {
        return this.timeOfCreation;
    }

    /**
     * Setter for <code>public.balance_entry.time_of_creation</code>.
     */
    public void setTimeOfCreation(LocalTime timeOfCreation) {
        this.timeOfCreation = timeOfCreation;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final BalanceEntry other = (BalanceEntry) obj;
        if (this.balanceEntryId == null) {
            if (other.balanceEntryId != null)
                return false;
        }
        else if (!this.balanceEntryId.equals(other.balanceEntryId))
            return false;
        if (this.entrySide == null) {
            if (other.entrySide != null)
                return false;
        }
        else if (!this.entrySide.equals(other.entrySide))
            return false;
        if (this.cashRegisterId == null) {
            if (other.cashRegisterId != null)
                return false;
        }
        else if (!this.cashRegisterId.equals(other.cashRegisterId))
            return false;
        if (this.entryTypeId == null) {
            if (other.entryTypeId != null)
                return false;
        }
        else if (!this.entryTypeId.equals(other.entryTypeId))
            return false;
        if (this.currencyCode == null) {
            if (other.currencyCode != null)
                return false;
        }
        else if (!this.currencyCode.equals(other.currencyCode))
            return false;
        if (this.amount == null) {
            if (other.amount != null)
                return false;
        }
        else if (!this.amount.equals(other.amount))
            return false;
        if (this.jobTypeId == null) {
            if (other.jobTypeId != null)
                return false;
        }
        else if (!this.jobTypeId.equals(other.jobTypeId))
            return false;
        if (this.jobId == null) {
            if (other.jobId != null)
                return false;
        }
        else if (!this.jobId.equals(other.jobId))
            return false;
        if (this.workPlaceId == null) {
            if (other.workPlaceId != null)
                return false;
        }
        else if (!this.workPlaceId.equals(other.workPlaceId))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.timestampOfCreation == null) {
            if (other.timestampOfCreation != null)
                return false;
        }
        else if (!this.timestampOfCreation.equals(other.timestampOfCreation))
            return false;
        if (this.dateOfCreation == null) {
            if (other.dateOfCreation != null)
                return false;
        }
        else if (!this.dateOfCreation.equals(other.dateOfCreation))
            return false;
        if (this.timeOfCreation == null) {
            if (other.timeOfCreation != null)
                return false;
        }
        else if (!this.timeOfCreation.equals(other.timeOfCreation))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.balanceEntryId == null) ? 0 : this.balanceEntryId.hashCode());
        result = prime * result + ((this.entrySide == null) ? 0 : this.entrySide.hashCode());
        result = prime * result + ((this.cashRegisterId == null) ? 0 : this.cashRegisterId.hashCode());
        result = prime * result + ((this.entryTypeId == null) ? 0 : this.entryTypeId.hashCode());
        result = prime * result + ((this.currencyCode == null) ? 0 : this.currencyCode.hashCode());
        result = prime * result + ((this.amount == null) ? 0 : this.amount.hashCode());
        result = prime * result + ((this.jobTypeId == null) ? 0 : this.jobTypeId.hashCode());
        result = prime * result + ((this.jobId == null) ? 0 : this.jobId.hashCode());
        result = prime * result + ((this.workPlaceId == null) ? 0 : this.workPlaceId.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.timestampOfCreation == null) ? 0 : this.timestampOfCreation.hashCode());
        result = prime * result + ((this.dateOfCreation == null) ? 0 : this.dateOfCreation.hashCode());
        result = prime * result + ((this.timeOfCreation == null) ? 0 : this.timeOfCreation.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BalanceEntry (");

        sb.append(balanceEntryId);
        sb.append(", ").append(entrySide);
        sb.append(", ").append(cashRegisterId);
        sb.append(", ").append(entryTypeId);
        sb.append(", ").append(currencyCode);
        sb.append(", ").append(amount);
        sb.append(", ").append(jobTypeId);
        sb.append(", ").append(jobId);
        sb.append(", ").append(workPlaceId);
        sb.append(", ").append(userId);
        sb.append(", ").append(timestampOfCreation);
        sb.append(", ").append(dateOfCreation);
        sb.append(", ").append(timeOfCreation);

        sb.append(")");
        return sb.toString();
    }
}
