/*
 * This file is generated by jOOQ.
 */
package PlatniPrometDB.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExchangeCashDenomination implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long exchangeCashDenominationId;
    private Long exchangeJobId;
    private Integer x1;
    private Integer x2;
    private Integer x5;
    private Integer x10;
    private Integer x20;
    private Integer x50;
    private Integer x100;
    private Integer x200;
    private Integer x500;
    private Integer x1000;
    private Integer x2000;
    private Integer x5000;

    public ExchangeCashDenomination() {}

    public ExchangeCashDenomination(ExchangeCashDenomination value) {
        this.exchangeCashDenominationId = value.exchangeCashDenominationId;
        this.exchangeJobId = value.exchangeJobId;
        this.x1 = value.x1;
        this.x2 = value.x2;
        this.x5 = value.x5;
        this.x10 = value.x10;
        this.x20 = value.x20;
        this.x50 = value.x50;
        this.x100 = value.x100;
        this.x200 = value.x200;
        this.x500 = value.x500;
        this.x1000 = value.x1000;
        this.x2000 = value.x2000;
        this.x5000 = value.x5000;
    }

    public ExchangeCashDenomination(
        Long exchangeCashDenominationId,
        Long exchangeJobId,
        Integer x1,
        Integer x2,
        Integer x5,
        Integer x10,
        Integer x20,
        Integer x50,
        Integer x100,
        Integer x200,
        Integer x500,
        Integer x1000,
        Integer x2000,
        Integer x5000
    ) {
        this.exchangeCashDenominationId = exchangeCashDenominationId;
        this.exchangeJobId = exchangeJobId;
        this.x1 = x1;
        this.x2 = x2;
        this.x5 = x5;
        this.x10 = x10;
        this.x20 = x20;
        this.x50 = x50;
        this.x100 = x100;
        this.x200 = x200;
        this.x500 = x500;
        this.x1000 = x1000;
        this.x2000 = x2000;
        this.x5000 = x5000;
    }

    /**
     * Getter for
     * <code>public.exchange_cash_denomination.exchange_cash_denomination_id</code>.
     */
    public Long getExchangeCashDenominationId() {
        return this.exchangeCashDenominationId;
    }

    /**
     * Setter for
     * <code>public.exchange_cash_denomination.exchange_cash_denomination_id</code>.
     */
    public void setExchangeCashDenominationId(Long exchangeCashDenominationId) {
        this.exchangeCashDenominationId = exchangeCashDenominationId;
    }

    /**
     * Getter for
     * <code>public.exchange_cash_denomination.exchange_job_id</code>.
     */
    public Long getExchangeJobId() {
        return this.exchangeJobId;
    }

    /**
     * Setter for
     * <code>public.exchange_cash_denomination.exchange_job_id</code>.
     */
    public void setExchangeJobId(Long exchangeJobId) {
        this.exchangeJobId = exchangeJobId;
    }

    /**
     * Getter for <code>public.exchange_cash_denomination.x1</code>.
     */
    public Integer getX1() {
        return this.x1;
    }

    /**
     * Setter for <code>public.exchange_cash_denomination.x1</code>.
     */
    public void setX1(Integer x1) {
        this.x1 = x1;
    }

    /**
     * Getter for <code>public.exchange_cash_denomination.x2</code>.
     */
    public Integer getX2() {
        return this.x2;
    }

    /**
     * Setter for <code>public.exchange_cash_denomination.x2</code>.
     */
    public void setX2(Integer x2) {
        this.x2 = x2;
    }

    /**
     * Getter for <code>public.exchange_cash_denomination.x5</code>.
     */
    public Integer getX5() {
        return this.x5;
    }

    /**
     * Setter for <code>public.exchange_cash_denomination.x5</code>.
     */
    public void setX5(Integer x5) {
        this.x5 = x5;
    }

    /**
     * Getter for <code>public.exchange_cash_denomination.x10</code>.
     */
    public Integer getX10() {
        return this.x10;
    }

    /**
     * Setter for <code>public.exchange_cash_denomination.x10</code>.
     */
    public void setX10(Integer x10) {
        this.x10 = x10;
    }

    /**
     * Getter for <code>public.exchange_cash_denomination.x20</code>.
     */
    public Integer getX20() {
        return this.x20;
    }

    /**
     * Setter for <code>public.exchange_cash_denomination.x20</code>.
     */
    public void setX20(Integer x20) {
        this.x20 = x20;
    }

    /**
     * Getter for <code>public.exchange_cash_denomination.x50</code>.
     */
    public Integer getX50() {
        return this.x50;
    }

    /**
     * Setter for <code>public.exchange_cash_denomination.x50</code>.
     */
    public void setX50(Integer x50) {
        this.x50 = x50;
    }

    /**
     * Getter for <code>public.exchange_cash_denomination.x100</code>.
     */
    public Integer getX100() {
        return this.x100;
    }

    /**
     * Setter for <code>public.exchange_cash_denomination.x100</code>.
     */
    public void setX100(Integer x100) {
        this.x100 = x100;
    }

    /**
     * Getter for <code>public.exchange_cash_denomination.x200</code>.
     */
    public Integer getX200() {
        return this.x200;
    }

    /**
     * Setter for <code>public.exchange_cash_denomination.x200</code>.
     */
    public void setX200(Integer x200) {
        this.x200 = x200;
    }

    /**
     * Getter for <code>public.exchange_cash_denomination.x500</code>.
     */
    public Integer getX500() {
        return this.x500;
    }

    /**
     * Setter for <code>public.exchange_cash_denomination.x500</code>.
     */
    public void setX500(Integer x500) {
        this.x500 = x500;
    }

    /**
     * Getter for <code>public.exchange_cash_denomination.x1000</code>.
     */
    public Integer getX1000() {
        return this.x1000;
    }

    /**
     * Setter for <code>public.exchange_cash_denomination.x1000</code>.
     */
    public void setX1000(Integer x1000) {
        this.x1000 = x1000;
    }

    /**
     * Getter for <code>public.exchange_cash_denomination.x2000</code>.
     */
    public Integer getX2000() {
        return this.x2000;
    }

    /**
     * Setter for <code>public.exchange_cash_denomination.x2000</code>.
     */
    public void setX2000(Integer x2000) {
        this.x2000 = x2000;
    }

    /**
     * Getter for <code>public.exchange_cash_denomination.x5000</code>.
     */
    public Integer getX5000() {
        return this.x5000;
    }

    /**
     * Setter for <code>public.exchange_cash_denomination.x5000</code>.
     */
    public void setX5000(Integer x5000) {
        this.x5000 = x5000;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ExchangeCashDenomination other = (ExchangeCashDenomination) obj;
        if (this.exchangeCashDenominationId == null) {
            if (other.exchangeCashDenominationId != null)
                return false;
        }
        else if (!this.exchangeCashDenominationId.equals(other.exchangeCashDenominationId))
            return false;
        if (this.exchangeJobId == null) {
            if (other.exchangeJobId != null)
                return false;
        }
        else if (!this.exchangeJobId.equals(other.exchangeJobId))
            return false;
        if (this.x1 == null) {
            if (other.x1 != null)
                return false;
        }
        else if (!this.x1.equals(other.x1))
            return false;
        if (this.x2 == null) {
            if (other.x2 != null)
                return false;
        }
        else if (!this.x2.equals(other.x2))
            return false;
        if (this.x5 == null) {
            if (other.x5 != null)
                return false;
        }
        else if (!this.x5.equals(other.x5))
            return false;
        if (this.x10 == null) {
            if (other.x10 != null)
                return false;
        }
        else if (!this.x10.equals(other.x10))
            return false;
        if (this.x20 == null) {
            if (other.x20 != null)
                return false;
        }
        else if (!this.x20.equals(other.x20))
            return false;
        if (this.x50 == null) {
            if (other.x50 != null)
                return false;
        }
        else if (!this.x50.equals(other.x50))
            return false;
        if (this.x100 == null) {
            if (other.x100 != null)
                return false;
        }
        else if (!this.x100.equals(other.x100))
            return false;
        if (this.x200 == null) {
            if (other.x200 != null)
                return false;
        }
        else if (!this.x200.equals(other.x200))
            return false;
        if (this.x500 == null) {
            if (other.x500 != null)
                return false;
        }
        else if (!this.x500.equals(other.x500))
            return false;
        if (this.x1000 == null) {
            if (other.x1000 != null)
                return false;
        }
        else if (!this.x1000.equals(other.x1000))
            return false;
        if (this.x2000 == null) {
            if (other.x2000 != null)
                return false;
        }
        else if (!this.x2000.equals(other.x2000))
            return false;
        if (this.x5000 == null) {
            if (other.x5000 != null)
                return false;
        }
        else if (!this.x5000.equals(other.x5000))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.exchangeCashDenominationId == null) ? 0 : this.exchangeCashDenominationId.hashCode());
        result = prime * result + ((this.exchangeJobId == null) ? 0 : this.exchangeJobId.hashCode());
        result = prime * result + ((this.x1 == null) ? 0 : this.x1.hashCode());
        result = prime * result + ((this.x2 == null) ? 0 : this.x2.hashCode());
        result = prime * result + ((this.x5 == null) ? 0 : this.x5.hashCode());
        result = prime * result + ((this.x10 == null) ? 0 : this.x10.hashCode());
        result = prime * result + ((this.x20 == null) ? 0 : this.x20.hashCode());
        result = prime * result + ((this.x50 == null) ? 0 : this.x50.hashCode());
        result = prime * result + ((this.x100 == null) ? 0 : this.x100.hashCode());
        result = prime * result + ((this.x200 == null) ? 0 : this.x200.hashCode());
        result = prime * result + ((this.x500 == null) ? 0 : this.x500.hashCode());
        result = prime * result + ((this.x1000 == null) ? 0 : this.x1000.hashCode());
        result = prime * result + ((this.x2000 == null) ? 0 : this.x2000.hashCode());
        result = prime * result + ((this.x5000 == null) ? 0 : this.x5000.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ExchangeCashDenomination (");

        sb.append(exchangeCashDenominationId);
        sb.append(", ").append(exchangeJobId);
        sb.append(", ").append(x1);
        sb.append(", ").append(x2);
        sb.append(", ").append(x5);
        sb.append(", ").append(x10);
        sb.append(", ").append(x20);
        sb.append(", ").append(x50);
        sb.append(", ").append(x100);
        sb.append(", ").append(x200);
        sb.append(", ").append(x500);
        sb.append(", ").append(x1000);
        sb.append(", ").append(x2000);
        sb.append(", ").append(x5000);

        sb.append(")");
        return sb.toString();
    }
}
