/*
 * This file is generated by jOOQ.
 */
package PlatniPrometDB.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExchangeJob implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long exchangeJobId;
    private Long jobTypeId;
    private BigDecimal receivedAmount;
    private Integer receivedCurrencyCode;
    private Long exchangeRateEntryId;
    private BigDecimal middleRateAmount;
    private BigDecimal exchangeAmount;
    private Long exchangeCashDenominationId;
    private Long userId;
    private OffsetDateTime timestampOfCreation;
    private LocalDate dateOfCreation;
    private LocalTime timeOfCreation;

    public ExchangeJob() {}

    public ExchangeJob(ExchangeJob value) {
        this.exchangeJobId = value.exchangeJobId;
        this.jobTypeId = value.jobTypeId;
        this.receivedAmount = value.receivedAmount;
        this.receivedCurrencyCode = value.receivedCurrencyCode;
        this.exchangeRateEntryId = value.exchangeRateEntryId;
        this.middleRateAmount = value.middleRateAmount;
        this.exchangeAmount = value.exchangeAmount;
        this.exchangeCashDenominationId = value.exchangeCashDenominationId;
        this.userId = value.userId;
        this.timestampOfCreation = value.timestampOfCreation;
        this.dateOfCreation = value.dateOfCreation;
        this.timeOfCreation = value.timeOfCreation;
    }

    public ExchangeJob(
        Long exchangeJobId,
        Long jobTypeId,
        BigDecimal receivedAmount,
        Integer receivedCurrencyCode,
        Long exchangeRateEntryId,
        BigDecimal middleRateAmount,
        BigDecimal exchangeAmount,
        Long exchangeCashDenominationId,
        Long userId,
        OffsetDateTime timestampOfCreation,
        LocalDate dateOfCreation,
        LocalTime timeOfCreation
    ) {
        this.exchangeJobId = exchangeJobId;
        this.jobTypeId = jobTypeId;
        this.receivedAmount = receivedAmount;
        this.receivedCurrencyCode = receivedCurrencyCode;
        this.exchangeRateEntryId = exchangeRateEntryId;
        this.middleRateAmount = middleRateAmount;
        this.exchangeAmount = exchangeAmount;
        this.exchangeCashDenominationId = exchangeCashDenominationId;
        this.userId = userId;
        this.timestampOfCreation = timestampOfCreation;
        this.dateOfCreation = dateOfCreation;
        this.timeOfCreation = timeOfCreation;
    }

    /**
     * Getter for <code>public.exchange_job.exchange_job_id</code>.
     */
    public Long getExchangeJobId() {
        return this.exchangeJobId;
    }

    /**
     * Setter for <code>public.exchange_job.exchange_job_id</code>.
     */
    public void setExchangeJobId(Long exchangeJobId) {
        this.exchangeJobId = exchangeJobId;
    }

    /**
     * Getter for <code>public.exchange_job.job_type_id</code>. 1 - Buy, 2 -
     * Sell
     */
    public Long getJobTypeId() {
        return this.jobTypeId;
    }

    /**
     * Setter for <code>public.exchange_job.job_type_id</code>. 1 - Buy, 2 -
     * Sell
     */
    public void setJobTypeId(Long jobTypeId) {
        this.jobTypeId = jobTypeId;
    }

    /**
     * Getter for <code>public.exchange_job.received_amount</code>.
     */
    public BigDecimal getReceivedAmount() {
        return this.receivedAmount;
    }

    /**
     * Setter for <code>public.exchange_job.received_amount</code>.
     */
    public void setReceivedAmount(BigDecimal receivedAmount) {
        this.receivedAmount = receivedAmount;
    }

    /**
     * Getter for <code>public.exchange_job.received_currency_code</code>.
     */
    public Integer getReceivedCurrencyCode() {
        return this.receivedCurrencyCode;
    }

    /**
     * Setter for <code>public.exchange_job.received_currency_code</code>.
     */
    public void setReceivedCurrencyCode(Integer receivedCurrencyCode) {
        this.receivedCurrencyCode = receivedCurrencyCode;
    }

    /**
     * Getter for <code>public.exchange_job.exchange_rate_entry_id</code>.
     */
    public Long getExchangeRateEntryId() {
        return this.exchangeRateEntryId;
    }

    /**
     * Setter for <code>public.exchange_job.exchange_rate_entry_id</code>.
     */
    public void setExchangeRateEntryId(Long exchangeRateEntryId) {
        this.exchangeRateEntryId = exchangeRateEntryId;
    }

    /**
     * Getter for <code>public.exchange_job.middle_rate_amount</code>.
     */
    public BigDecimal getMiddleRateAmount() {
        return this.middleRateAmount;
    }

    /**
     * Setter for <code>public.exchange_job.middle_rate_amount</code>.
     */
    public void setMiddleRateAmount(BigDecimal middleRateAmount) {
        this.middleRateAmount = middleRateAmount;
    }

    /**
     * Getter for <code>public.exchange_job.exchange_amount</code>.
     */
    public BigDecimal getExchangeAmount() {
        return this.exchangeAmount;
    }

    /**
     * Setter for <code>public.exchange_job.exchange_amount</code>.
     */
    public void setExchangeAmount(BigDecimal exchangeAmount) {
        this.exchangeAmount = exchangeAmount;
    }

    /**
     * Getter for
     * <code>public.exchange_job.exchange_cash_denomination_id</code>.
     */
    public Long getExchangeCashDenominationId() {
        return this.exchangeCashDenominationId;
    }

    /**
     * Setter for
     * <code>public.exchange_job.exchange_cash_denomination_id</code>.
     */
    public void setExchangeCashDenominationId(Long exchangeCashDenominationId) {
        this.exchangeCashDenominationId = exchangeCashDenominationId;
    }

    /**
     * Getter for <code>public.exchange_job.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.exchange_job.user_id</code>.
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>public.exchange_job.timestamp_of_creation</code>.
     */
    public OffsetDateTime getTimestampOfCreation() {
        return this.timestampOfCreation;
    }

    /**
     * Setter for <code>public.exchange_job.timestamp_of_creation</code>.
     */
    public void setTimestampOfCreation(OffsetDateTime timestampOfCreation) {
        this.timestampOfCreation = timestampOfCreation;
    }

    /**
     * Getter for <code>public.exchange_job.date_of_creation</code>.
     */
    public LocalDate getDateOfCreation() {
        return this.dateOfCreation;
    }

    /**
     * Setter for <code>public.exchange_job.date_of_creation</code>.
     */
    public void setDateOfCreation(LocalDate dateOfCreation) {
        this.dateOfCreation = dateOfCreation;
    }

    /**
     * Getter for <code>public.exchange_job.time_of_creation</code>.
     */
    public LocalTime getTimeOfCreation() {
        return this.timeOfCreation;
    }

    /**
     * Setter for <code>public.exchange_job.time_of_creation</code>.
     */
    public void setTimeOfCreation(LocalTime timeOfCreation) {
        this.timeOfCreation = timeOfCreation;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ExchangeJob other = (ExchangeJob) obj;
        if (this.exchangeJobId == null) {
            if (other.exchangeJobId != null)
                return false;
        }
        else if (!this.exchangeJobId.equals(other.exchangeJobId))
            return false;
        if (this.jobTypeId == null) {
            if (other.jobTypeId != null)
                return false;
        }
        else if (!this.jobTypeId.equals(other.jobTypeId))
            return false;
        if (this.receivedAmount == null) {
            if (other.receivedAmount != null)
                return false;
        }
        else if (!this.receivedAmount.equals(other.receivedAmount))
            return false;
        if (this.receivedCurrencyCode == null) {
            if (other.receivedCurrencyCode != null)
                return false;
        }
        else if (!this.receivedCurrencyCode.equals(other.receivedCurrencyCode))
            return false;
        if (this.exchangeRateEntryId == null) {
            if (other.exchangeRateEntryId != null)
                return false;
        }
        else if (!this.exchangeRateEntryId.equals(other.exchangeRateEntryId))
            return false;
        if (this.middleRateAmount == null) {
            if (other.middleRateAmount != null)
                return false;
        }
        else if (!this.middleRateAmount.equals(other.middleRateAmount))
            return false;
        if (this.exchangeAmount == null) {
            if (other.exchangeAmount != null)
                return false;
        }
        else if (!this.exchangeAmount.equals(other.exchangeAmount))
            return false;
        if (this.exchangeCashDenominationId == null) {
            if (other.exchangeCashDenominationId != null)
                return false;
        }
        else if (!this.exchangeCashDenominationId.equals(other.exchangeCashDenominationId))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.timestampOfCreation == null) {
            if (other.timestampOfCreation != null)
                return false;
        }
        else if (!this.timestampOfCreation.equals(other.timestampOfCreation))
            return false;
        if (this.dateOfCreation == null) {
            if (other.dateOfCreation != null)
                return false;
        }
        else if (!this.dateOfCreation.equals(other.dateOfCreation))
            return false;
        if (this.timeOfCreation == null) {
            if (other.timeOfCreation != null)
                return false;
        }
        else if (!this.timeOfCreation.equals(other.timeOfCreation))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.exchangeJobId == null) ? 0 : this.exchangeJobId.hashCode());
        result = prime * result + ((this.jobTypeId == null) ? 0 : this.jobTypeId.hashCode());
        result = prime * result + ((this.receivedAmount == null) ? 0 : this.receivedAmount.hashCode());
        result = prime * result + ((this.receivedCurrencyCode == null) ? 0 : this.receivedCurrencyCode.hashCode());
        result = prime * result + ((this.exchangeRateEntryId == null) ? 0 : this.exchangeRateEntryId.hashCode());
        result = prime * result + ((this.middleRateAmount == null) ? 0 : this.middleRateAmount.hashCode());
        result = prime * result + ((this.exchangeAmount == null) ? 0 : this.exchangeAmount.hashCode());
        result = prime * result + ((this.exchangeCashDenominationId == null) ? 0 : this.exchangeCashDenominationId.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.timestampOfCreation == null) ? 0 : this.timestampOfCreation.hashCode());
        result = prime * result + ((this.dateOfCreation == null) ? 0 : this.dateOfCreation.hashCode());
        result = prime * result + ((this.timeOfCreation == null) ? 0 : this.timeOfCreation.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ExchangeJob (");

        sb.append(exchangeJobId);
        sb.append(", ").append(jobTypeId);
        sb.append(", ").append(receivedAmount);
        sb.append(", ").append(receivedCurrencyCode);
        sb.append(", ").append(exchangeRateEntryId);
        sb.append(", ").append(middleRateAmount);
        sb.append(", ").append(exchangeAmount);
        sb.append(", ").append(exchangeCashDenominationId);
        sb.append(", ").append(userId);
        sb.append(", ").append(timestampOfCreation);
        sb.append(", ").append(dateOfCreation);
        sb.append(", ").append(timeOfCreation);

        sb.append(")");
        return sb.toString();
    }
}
