/*
 * This file is generated by jOOQ.
 */
package PlatniPrometDB.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobType implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long jobTypeId;
    private String name;
    private String description;

    public JobType() {}

    public JobType(JobType value) {
        this.jobTypeId = value.jobTypeId;
        this.name = value.name;
        this.description = value.description;
    }

    public JobType(
        Long jobTypeId,
        String name,
        String description
    ) {
        this.jobTypeId = jobTypeId;
        this.name = name;
        this.description = description;
    }

    /**
     * Getter for <code>public.job_type.job_type_id</code>.
     */
    public Long getJobTypeId() {
        return this.jobTypeId;
    }

    /**
     * Setter for <code>public.job_type.job_type_id</code>.
     */
    public void setJobTypeId(Long jobTypeId) {
        this.jobTypeId = jobTypeId;
    }

    /**
     * Getter for <code>public.job_type.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.job_type.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.job_type.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>public.job_type.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final JobType other = (JobType) obj;
        if (this.jobTypeId == null) {
            if (other.jobTypeId != null)
                return false;
        }
        else if (!this.jobTypeId.equals(other.jobTypeId))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.jobTypeId == null) ? 0 : this.jobTypeId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JobType (");

        sb.append(jobTypeId);
        sb.append(", ").append(name);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
