/*
 * This file is generated by jOOQ.
 */
package PlatniPrometDB.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Organisation implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long organisationId;
    private String name;
    private String legalId;
    private String address;
    private String city;
    private String phoneNumber;
    private LocalDateTime timestampOfCreation;

    public Organisation() {}

    public Organisation(Organisation value) {
        this.organisationId = value.organisationId;
        this.name = value.name;
        this.legalId = value.legalId;
        this.address = value.address;
        this.city = value.city;
        this.phoneNumber = value.phoneNumber;
        this.timestampOfCreation = value.timestampOfCreation;
    }

    public Organisation(
        Long organisationId,
        String name,
        String legalId,
        String address,
        String city,
        String phoneNumber,
        LocalDateTime timestampOfCreation
    ) {
        this.organisationId = organisationId;
        this.name = name;
        this.legalId = legalId;
        this.address = address;
        this.city = city;
        this.phoneNumber = phoneNumber;
        this.timestampOfCreation = timestampOfCreation;
    }

    /**
     * Getter for <code>public.organisation.organisation_id</code>.
     */
    public Long getOrganisationId() {
        return this.organisationId;
    }

    /**
     * Setter for <code>public.organisation.organisation_id</code>.
     */
    public void setOrganisationId(Long organisationId) {
        this.organisationId = organisationId;
    }

    /**
     * Getter for <code>public.organisation.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.organisation.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.organisation.legal_id</code>.
     */
    public String getLegalId() {
        return this.legalId;
    }

    /**
     * Setter for <code>public.organisation.legal_id</code>.
     */
    public void setLegalId(String legalId) {
        this.legalId = legalId;
    }

    /**
     * Getter for <code>public.organisation.address</code>.
     */
    public String getAddress() {
        return this.address;
    }

    /**
     * Setter for <code>public.organisation.address</code>.
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * Getter for <code>public.organisation.city</code>.
     */
    public String getCity() {
        return this.city;
    }

    /**
     * Setter for <code>public.organisation.city</code>.
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * Getter for <code>public.organisation.phone_number</code>.
     */
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    /**
     * Setter for <code>public.organisation.phone_number</code>.
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * Getter for <code>public.organisation.timestamp_of_creation</code>.
     */
    public LocalDateTime getTimestampOfCreation() {
        return this.timestampOfCreation;
    }

    /**
     * Setter for <code>public.organisation.timestamp_of_creation</code>.
     */
    public void setTimestampOfCreation(LocalDateTime timestampOfCreation) {
        this.timestampOfCreation = timestampOfCreation;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Organisation other = (Organisation) obj;
        if (this.organisationId == null) {
            if (other.organisationId != null)
                return false;
        }
        else if (!this.organisationId.equals(other.organisationId))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.legalId == null) {
            if (other.legalId != null)
                return false;
        }
        else if (!this.legalId.equals(other.legalId))
            return false;
        if (this.address == null) {
            if (other.address != null)
                return false;
        }
        else if (!this.address.equals(other.address))
            return false;
        if (this.city == null) {
            if (other.city != null)
                return false;
        }
        else if (!this.city.equals(other.city))
            return false;
        if (this.phoneNumber == null) {
            if (other.phoneNumber != null)
                return false;
        }
        else if (!this.phoneNumber.equals(other.phoneNumber))
            return false;
        if (this.timestampOfCreation == null) {
            if (other.timestampOfCreation != null)
                return false;
        }
        else if (!this.timestampOfCreation.equals(other.timestampOfCreation))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.organisationId == null) ? 0 : this.organisationId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.legalId == null) ? 0 : this.legalId.hashCode());
        result = prime * result + ((this.address == null) ? 0 : this.address.hashCode());
        result = prime * result + ((this.city == null) ? 0 : this.city.hashCode());
        result = prime * result + ((this.phoneNumber == null) ? 0 : this.phoneNumber.hashCode());
        result = prime * result + ((this.timestampOfCreation == null) ? 0 : this.timestampOfCreation.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Organisation (");

        sb.append(organisationId);
        sb.append(", ").append(name);
        sb.append(", ").append(legalId);
        sb.append(", ").append(address);
        sb.append(", ").append(city);
        sb.append(", ").append(phoneNumber);
        sb.append(", ").append(timestampOfCreation);

        sb.append(")");
        return sb.toString();
    }
}
