/*
 * This file is generated by jOOQ.
 */
package PlatniPrometDB.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long userId;
    private String username;
    private Integer roleId;
    private Boolean flActive;
    private LocalDate dateOfStart;
    private LocalDate dateOfEnd;
    private LocalDateTime timestampOfCreation;

    public User() {}

    public User(User value) {
        this.userId = value.userId;
        this.username = value.username;
        this.roleId = value.roleId;
        this.flActive = value.flActive;
        this.dateOfStart = value.dateOfStart;
        this.dateOfEnd = value.dateOfEnd;
        this.timestampOfCreation = value.timestampOfCreation;
    }

    public User(
        Long userId,
        String username,
        Integer roleId,
        Boolean flActive,
        LocalDate dateOfStart,
        LocalDate dateOfEnd,
        LocalDateTime timestampOfCreation
    ) {
        this.userId = userId;
        this.username = username;
        this.roleId = roleId;
        this.flActive = flActive;
        this.dateOfStart = dateOfStart;
        this.dateOfEnd = dateOfEnd;
        this.timestampOfCreation = timestampOfCreation;
    }

    /**
     * Getter for <code>public.user.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.user.user_id</code>.
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>public.user.username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>public.user.username</code>.
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Getter for <code>public.user.role_id</code>.
     */
    public Integer getRoleId() {
        return this.roleId;
    }

    /**
     * Setter for <code>public.user.role_id</code>.
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * Getter for <code>public.user.fl_active</code>.
     */
    public Boolean getFlActive() {
        return this.flActive;
    }

    /**
     * Setter for <code>public.user.fl_active</code>.
     */
    public void setFlActive(Boolean flActive) {
        this.flActive = flActive;
    }

    /**
     * Getter for <code>public.user.date_of_start</code>.
     */
    public LocalDate getDateOfStart() {
        return this.dateOfStart;
    }

    /**
     * Setter for <code>public.user.date_of_start</code>.
     */
    public void setDateOfStart(LocalDate dateOfStart) {
        this.dateOfStart = dateOfStart;
    }

    /**
     * Getter for <code>public.user.date_of_end</code>.
     */
    public LocalDate getDateOfEnd() {
        return this.dateOfEnd;
    }

    /**
     * Setter for <code>public.user.date_of_end</code>.
     */
    public void setDateOfEnd(LocalDate dateOfEnd) {
        this.dateOfEnd = dateOfEnd;
    }

    /**
     * Getter for <code>public.user.timestamp_of_creation</code>.
     */
    public LocalDateTime getTimestampOfCreation() {
        return this.timestampOfCreation;
    }

    /**
     * Setter for <code>public.user.timestamp_of_creation</code>.
     */
    public void setTimestampOfCreation(LocalDateTime timestampOfCreation) {
        this.timestampOfCreation = timestampOfCreation;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final User other = (User) obj;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.username == null) {
            if (other.username != null)
                return false;
        }
        else if (!this.username.equals(other.username))
            return false;
        if (this.roleId == null) {
            if (other.roleId != null)
                return false;
        }
        else if (!this.roleId.equals(other.roleId))
            return false;
        if (this.flActive == null) {
            if (other.flActive != null)
                return false;
        }
        else if (!this.flActive.equals(other.flActive))
            return false;
        if (this.dateOfStart == null) {
            if (other.dateOfStart != null)
                return false;
        }
        else if (!this.dateOfStart.equals(other.dateOfStart))
            return false;
        if (this.dateOfEnd == null) {
            if (other.dateOfEnd != null)
                return false;
        }
        else if (!this.dateOfEnd.equals(other.dateOfEnd))
            return false;
        if (this.timestampOfCreation == null) {
            if (other.timestampOfCreation != null)
                return false;
        }
        else if (!this.timestampOfCreation.equals(other.timestampOfCreation))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.username == null) ? 0 : this.username.hashCode());
        result = prime * result + ((this.roleId == null) ? 0 : this.roleId.hashCode());
        result = prime * result + ((this.flActive == null) ? 0 : this.flActive.hashCode());
        result = prime * result + ((this.dateOfStart == null) ? 0 : this.dateOfStart.hashCode());
        result = prime * result + ((this.dateOfEnd == null) ? 0 : this.dateOfEnd.hashCode());
        result = prime * result + ((this.timestampOfCreation == null) ? 0 : this.timestampOfCreation.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(userId);
        sb.append(", ").append(username);
        sb.append(", ").append(roleId);
        sb.append(", ").append(flActive);
        sb.append(", ").append(dateOfStart);
        sb.append(", ").append(dateOfEnd);
        sb.append(", ").append(timestampOfCreation);

        sb.append(")");
        return sb.toString();
    }
}
