/*
 * This file is generated by jOOQ.
 */
package PlatniPrometDB.tables.daos;


import PlatniPrometDB.tables.CashRegister;
import PlatniPrometDB.tables.records.CashRegisterRecord;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CashRegisterDao extends DAOImpl<CashRegisterRecord, PlatniPrometDB.tables.pojos.CashRegister, Long> {

    /**
     * Create a new CashRegisterDao without any configuration
     */
    public CashRegisterDao() {
        super(CashRegister.CASH_REGISTER, PlatniPrometDB.tables.pojos.CashRegister.class);
    }

    /**
     * Create a new CashRegisterDao with an attached configuration
     */
    public CashRegisterDao(Configuration configuration) {
        super(CashRegister.CASH_REGISTER, PlatniPrometDB.tables.pojos.CashRegister.class, configuration);
    }

    @Override
    public Long getId(PlatniPrometDB.tables.pojos.CashRegister object) {
        return object.getCashRegisterId();
    }

    /**
     * Fetch records that have <code>cash_register_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.CashRegister> fetchRangeOfCashRegisterId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(CashRegister.CASH_REGISTER.CASH_REGISTER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>cash_register_id IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.CashRegister> fetchByCashRegisterId(Long... values) {
        return fetch(CashRegister.CASH_REGISTER.CASH_REGISTER_ID, values);
    }

    /**
     * Fetch a unique record that has <code>cash_register_id = value</code>
     */
    public PlatniPrometDB.tables.pojos.CashRegister fetchOneByCashRegisterId(Long value) {
        return fetchOne(CashRegister.CASH_REGISTER.CASH_REGISTER_ID, value);
    }

    /**
     * Fetch a unique record that has <code>cash_register_id = value</code>
     */
    public Optional<PlatniPrometDB.tables.pojos.CashRegister> fetchOptionalByCashRegisterId(Long value) {
        return fetchOptional(CashRegister.CASH_REGISTER.CASH_REGISTER_ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.CashRegister> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(CashRegister.CASH_REGISTER.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.CashRegister> fetchByName(String... values) {
        return fetch(CashRegister.CASH_REGISTER.NAME, values);
    }

    /**
     * Fetch a unique record that has <code>name = value</code>
     */
    public PlatniPrometDB.tables.pojos.CashRegister fetchOneByName(String value) {
        return fetchOne(CashRegister.CASH_REGISTER.NAME, value);
    }

    /**
     * Fetch a unique record that has <code>name = value</code>
     */
    public Optional<PlatniPrometDB.tables.pojos.CashRegister> fetchOptionalByName(String value) {
        return fetchOptional(CashRegister.CASH_REGISTER.NAME, value);
    }

    /**
     * Fetch records that have <code>fl_active BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.CashRegister> fetchRangeOfFlActive(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(CashRegister.CASH_REGISTER.FL_ACTIVE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>fl_active IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.CashRegister> fetchByFlActive(Boolean... values) {
        return fetch(CashRegister.CASH_REGISTER.FL_ACTIVE, values);
    }

    /**
     * Fetch records that have <code>timestamp_of_creation BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.CashRegister> fetchRangeOfTimestampOfCreation(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(CashRegister.CASH_REGISTER.TIMESTAMP_OF_CREATION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>timestamp_of_creation IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.CashRegister> fetchByTimestampOfCreation(OffsetDateTime... values) {
        return fetch(CashRegister.CASH_REGISTER.TIMESTAMP_OF_CREATION, values);
    }

    /**
     * Fetch records that have <code>fl_in_use BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.CashRegister> fetchRangeOfFlInUse(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(CashRegister.CASH_REGISTER.FL_IN_USE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>fl_in_use IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.CashRegister> fetchByFlInUse(Boolean... values) {
        return fetch(CashRegister.CASH_REGISTER.FL_IN_USE, values);
    }

    /**
     * Fetch records that have <code>fl_treasury BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.CashRegister> fetchRangeOfFlTreasury(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(CashRegister.CASH_REGISTER.FL_TREASURY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>fl_treasury IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.CashRegister> fetchByFlTreasury(Boolean... values) {
        return fetch(CashRegister.CASH_REGISTER.FL_TREASURY, values);
    }
}
