/*
 * This file is generated by jOOQ.
 */
package PlatniPrometDB.tables.daos;


import PlatniPrometDB.tables.Currency;
import PlatniPrometDB.tables.records.CurrencyRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CurrencyDao extends DAOImpl<CurrencyRecord, PlatniPrometDB.tables.pojos.Currency, String> {

    /**
     * Create a new CurrencyDao without any configuration
     */
    public CurrencyDao() {
        super(Currency.CURRENCY, PlatniPrometDB.tables.pojos.Currency.class);
    }

    /**
     * Create a new CurrencyDao with an attached configuration
     */
    public CurrencyDao(Configuration configuration) {
        super(Currency.CURRENCY, PlatniPrometDB.tables.pojos.Currency.class, configuration);
    }

    @Override
    public String getId(PlatniPrometDB.tables.pojos.Currency object) {
        return object.getCurrencyCode();
    }

    /**
     * Fetch records that have <code>currency_code BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.Currency> fetchRangeOfCurrencyCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(Currency.CURRENCY.CURRENCY_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>currency_code IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.Currency> fetchByCurrencyCode(String... values) {
        return fetch(Currency.CURRENCY.CURRENCY_CODE, values);
    }

    /**
     * Fetch a unique record that has <code>currency_code = value</code>
     */
    public PlatniPrometDB.tables.pojos.Currency fetchOneByCurrencyCode(String value) {
        return fetchOne(Currency.CURRENCY.CURRENCY_CODE, value);
    }

    /**
     * Fetch a unique record that has <code>currency_code = value</code>
     */
    public Optional<PlatniPrometDB.tables.pojos.Currency> fetchOptionalByCurrencyCode(String value) {
        return fetchOptional(Currency.CURRENCY.CURRENCY_CODE, value);
    }

    /**
     * Fetch records that have <code>currency_name_code BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.Currency> fetchRangeOfCurrencyNameCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(Currency.CURRENCY.CURRENCY_NAME_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>currency_name_code IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.Currency> fetchByCurrencyNameCode(String... values) {
        return fetch(Currency.CURRENCY.CURRENCY_NAME_CODE, values);
    }

    /**
     * Fetch records that have <code>full_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.Currency> fetchRangeOfFullName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Currency.CURRENCY.FULL_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>full_name IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.Currency> fetchByFullName(String... values) {
        return fetch(Currency.CURRENCY.FULL_NAME, values);
    }

    /**
     * Fetch records that have <code>quantity BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.Currency> fetchRangeOfQuantity(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Currency.CURRENCY.QUANTITY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>quantity IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.Currency> fetchByQuantity(Integer... values) {
        return fetch(Currency.CURRENCY.QUANTITY, values);
    }

    /**
     * Fetch records that have <code>country BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.Currency> fetchRangeOfCountry(String lowerInclusive, String upperInclusive) {
        return fetchRange(Currency.CURRENCY.COUNTRY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>country IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.Currency> fetchByCountry(String... values) {
        return fetch(Currency.CURRENCY.COUNTRY, values);
    }

    /**
     * Fetch records that have <code>sign_logo BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.Currency> fetchRangeOfSignLogo(String lowerInclusive, String upperInclusive) {
        return fetchRange(Currency.CURRENCY.SIGN_LOGO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>sign_logo IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.Currency> fetchBySignLogo(String... values) {
        return fetch(Currency.CURRENCY.SIGN_LOGO, values);
    }
}
