/*
 * This file is generated by jOOQ.
 */
package PlatniPrometDB.tables.daos;


import PlatniPrometDB.tables.ExchangeCashDenomination;
import PlatniPrometDB.tables.records.ExchangeCashDenominationRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExchangeCashDenominationDao extends DAOImpl<ExchangeCashDenominationRecord, PlatniPrometDB.tables.pojos.ExchangeCashDenomination, Long> {

    /**
     * Create a new ExchangeCashDenominationDao without any configuration
     */
    public ExchangeCashDenominationDao() {
        super(ExchangeCashDenomination.EXCHANGE_CASH_DENOMINATION, PlatniPrometDB.tables.pojos.ExchangeCashDenomination.class);
    }

    /**
     * Create a new ExchangeCashDenominationDao with an attached configuration
     */
    public ExchangeCashDenominationDao(Configuration configuration) {
        super(ExchangeCashDenomination.EXCHANGE_CASH_DENOMINATION, PlatniPrometDB.tables.pojos.ExchangeCashDenomination.class, configuration);
    }

    @Override
    public Long getId(PlatniPrometDB.tables.pojos.ExchangeCashDenomination object) {
        return object.getExchangeCashDenominationId();
    }

    /**
     * Fetch records that have <code>exchange_cash_denomination_id BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeCashDenomination> fetchRangeOfExchangeCashDenominationId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ExchangeCashDenomination.EXCHANGE_CASH_DENOMINATION.EXCHANGE_CASH_DENOMINATION_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>exchange_cash_denomination_id IN
     * (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeCashDenomination> fetchByExchangeCashDenominationId(Long... values) {
        return fetch(ExchangeCashDenomination.EXCHANGE_CASH_DENOMINATION.EXCHANGE_CASH_DENOMINATION_ID, values);
    }

    /**
     * Fetch a unique record that has <code>exchange_cash_denomination_id =
     * value</code>
     */
    public PlatniPrometDB.tables.pojos.ExchangeCashDenomination fetchOneByExchangeCashDenominationId(Long value) {
        return fetchOne(ExchangeCashDenomination.EXCHANGE_CASH_DENOMINATION.EXCHANGE_CASH_DENOMINATION_ID, value);
    }

    /**
     * Fetch a unique record that has <code>exchange_cash_denomination_id =
     * value</code>
     */
    public Optional<PlatniPrometDB.tables.pojos.ExchangeCashDenomination> fetchOptionalByExchangeCashDenominationId(Long value) {
        return fetchOptional(ExchangeCashDenomination.EXCHANGE_CASH_DENOMINATION.EXCHANGE_CASH_DENOMINATION_ID, value);
    }

    /**
     * Fetch records that have <code>exchange_job_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeCashDenomination> fetchRangeOfExchangeJobId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ExchangeCashDenomination.EXCHANGE_CASH_DENOMINATION.EXCHANGE_JOB_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>exchange_job_id IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeCashDenomination> fetchByExchangeJobId(Long... values) {
        return fetch(ExchangeCashDenomination.EXCHANGE_CASH_DENOMINATION.EXCHANGE_JOB_ID, values);
    }

    /**
     * Fetch records that have <code>x1 BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeCashDenomination> fetchRangeOfX1(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ExchangeCashDenomination.EXCHANGE_CASH_DENOMINATION.X1, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>x1 IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeCashDenomination> fetchByX1(Integer... values) {
        return fetch(ExchangeCashDenomination.EXCHANGE_CASH_DENOMINATION.X1, values);
    }

    /**
     * Fetch records that have <code>x2 BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeCashDenomination> fetchRangeOfX2(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ExchangeCashDenomination.EXCHANGE_CASH_DENOMINATION.X2, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>x2 IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeCashDenomination> fetchByX2(Integer... values) {
        return fetch(ExchangeCashDenomination.EXCHANGE_CASH_DENOMINATION.X2, values);
    }

    /**
     * Fetch records that have <code>x5 BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeCashDenomination> fetchRangeOfX5(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ExchangeCashDenomination.EXCHANGE_CASH_DENOMINATION.X5, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>x5 IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeCashDenomination> fetchByX5(Integer... values) {
        return fetch(ExchangeCashDenomination.EXCHANGE_CASH_DENOMINATION.X5, values);
    }

    /**
     * Fetch records that have <code>x10 BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeCashDenomination> fetchRangeOfX10(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ExchangeCashDenomination.EXCHANGE_CASH_DENOMINATION.X10, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>x10 IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeCashDenomination> fetchByX10(Integer... values) {
        return fetch(ExchangeCashDenomination.EXCHANGE_CASH_DENOMINATION.X10, values);
    }

    /**
     * Fetch records that have <code>x20 BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeCashDenomination> fetchRangeOfX20(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ExchangeCashDenomination.EXCHANGE_CASH_DENOMINATION.X20, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>x20 IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeCashDenomination> fetchByX20(Integer... values) {
        return fetch(ExchangeCashDenomination.EXCHANGE_CASH_DENOMINATION.X20, values);
    }

    /**
     * Fetch records that have <code>x50 BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeCashDenomination> fetchRangeOfX50(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ExchangeCashDenomination.EXCHANGE_CASH_DENOMINATION.X50, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>x50 IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeCashDenomination> fetchByX50(Integer... values) {
        return fetch(ExchangeCashDenomination.EXCHANGE_CASH_DENOMINATION.X50, values);
    }

    /**
     * Fetch records that have <code>x100 BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeCashDenomination> fetchRangeOfX100(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ExchangeCashDenomination.EXCHANGE_CASH_DENOMINATION.X100, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>x100 IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeCashDenomination> fetchByX100(Integer... values) {
        return fetch(ExchangeCashDenomination.EXCHANGE_CASH_DENOMINATION.X100, values);
    }

    /**
     * Fetch records that have <code>x200 BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeCashDenomination> fetchRangeOfX200(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ExchangeCashDenomination.EXCHANGE_CASH_DENOMINATION.X200, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>x200 IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeCashDenomination> fetchByX200(Integer... values) {
        return fetch(ExchangeCashDenomination.EXCHANGE_CASH_DENOMINATION.X200, values);
    }

    /**
     * Fetch records that have <code>x500 BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeCashDenomination> fetchRangeOfX500(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ExchangeCashDenomination.EXCHANGE_CASH_DENOMINATION.X500, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>x500 IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeCashDenomination> fetchByX500(Integer... values) {
        return fetch(ExchangeCashDenomination.EXCHANGE_CASH_DENOMINATION.X500, values);
    }

    /**
     * Fetch records that have <code>x1000 BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeCashDenomination> fetchRangeOfX1000(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ExchangeCashDenomination.EXCHANGE_CASH_DENOMINATION.X1000, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>x1000 IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeCashDenomination> fetchByX1000(Integer... values) {
        return fetch(ExchangeCashDenomination.EXCHANGE_CASH_DENOMINATION.X1000, values);
    }

    /**
     * Fetch records that have <code>x2000 BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeCashDenomination> fetchRangeOfX2000(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ExchangeCashDenomination.EXCHANGE_CASH_DENOMINATION.X2000, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>x2000 IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeCashDenomination> fetchByX2000(Integer... values) {
        return fetch(ExchangeCashDenomination.EXCHANGE_CASH_DENOMINATION.X2000, values);
    }

    /**
     * Fetch records that have <code>x5000 BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeCashDenomination> fetchRangeOfX5000(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ExchangeCashDenomination.EXCHANGE_CASH_DENOMINATION.X5000, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>x5000 IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeCashDenomination> fetchByX5000(Integer... values) {
        return fetch(ExchangeCashDenomination.EXCHANGE_CASH_DENOMINATION.X5000, values);
    }
}
