/*
 * This file is generated by jOOQ.
 */
package PlatniPrometDB.tables.daos;


import PlatniPrometDB.tables.ExchangeRateEntry;
import PlatniPrometDB.tables.records.ExchangeRateEntryRecord;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExchangeRateEntryDao extends DAOImpl<ExchangeRateEntryRecord, PlatniPrometDB.tables.pojos.ExchangeRateEntry, Long> {

    /**
     * Create a new ExchangeRateEntryDao without any configuration
     */
    public ExchangeRateEntryDao() {
        super(ExchangeRateEntry.EXCHANGE_RATE_ENTRY, PlatniPrometDB.tables.pojos.ExchangeRateEntry.class);
    }

    /**
     * Create a new ExchangeRateEntryDao with an attached configuration
     */
    public ExchangeRateEntryDao(Configuration configuration) {
        super(ExchangeRateEntry.EXCHANGE_RATE_ENTRY, PlatniPrometDB.tables.pojos.ExchangeRateEntry.class, configuration);
    }

    @Override
    public Long getId(PlatniPrometDB.tables.pojos.ExchangeRateEntry object) {
        return object.getExchangeRateEntryId();
    }

    /**
     * Fetch records that have <code>exchange_rate_entry_id BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeRateEntry> fetchRangeOfExchangeRateEntryId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ExchangeRateEntry.EXCHANGE_RATE_ENTRY.EXCHANGE_RATE_ENTRY_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>exchange_rate_entry_id IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeRateEntry> fetchByExchangeRateEntryId(Long... values) {
        return fetch(ExchangeRateEntry.EXCHANGE_RATE_ENTRY.EXCHANGE_RATE_ENTRY_ID, values);
    }

    /**
     * Fetch a unique record that has <code>exchange_rate_entry_id =
     * value</code>
     */
    public PlatniPrometDB.tables.pojos.ExchangeRateEntry fetchOneByExchangeRateEntryId(Long value) {
        return fetchOne(ExchangeRateEntry.EXCHANGE_RATE_ENTRY.EXCHANGE_RATE_ENTRY_ID, value);
    }

    /**
     * Fetch a unique record that has <code>exchange_rate_entry_id =
     * value</code>
     */
    public Optional<PlatniPrometDB.tables.pojos.ExchangeRateEntry> fetchOptionalByExchangeRateEntryId(Long value) {
        return fetchOptional(ExchangeRateEntry.EXCHANGE_RATE_ENTRY.EXCHANGE_RATE_ENTRY_ID, value);
    }

    /**
     * Fetch records that have <code>exchange_rate_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeRateEntry> fetchRangeOfExchangeRateId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ExchangeRateEntry.EXCHANGE_RATE_ENTRY.EXCHANGE_RATE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>exchange_rate_id IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeRateEntry> fetchByExchangeRateId(Long... values) {
        return fetch(ExchangeRateEntry.EXCHANGE_RATE_ENTRY.EXCHANGE_RATE_ID, values);
    }

    /**
     * Fetch records that have <code>currency_code BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeRateEntry> fetchRangeOfCurrencyCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(ExchangeRateEntry.EXCHANGE_RATE_ENTRY.CURRENCY_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>currency_code IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeRateEntry> fetchByCurrencyCode(String... values) {
        return fetch(ExchangeRateEntry.EXCHANGE_RATE_ENTRY.CURRENCY_CODE, values);
    }

    /**
     * Fetch records that have <code>currency_name_code BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeRateEntry> fetchRangeOfCurrencyNameCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(ExchangeRateEntry.EXCHANGE_RATE_ENTRY.CURRENCY_NAME_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>currency_name_code IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeRateEntry> fetchByCurrencyNameCode(String... values) {
        return fetch(ExchangeRateEntry.EXCHANGE_RATE_ENTRY.CURRENCY_NAME_CODE, values);
    }

    /**
     * Fetch records that have <code>buy_rate BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeRateEntry> fetchRangeOfBuyRate(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(ExchangeRateEntry.EXCHANGE_RATE_ENTRY.BUY_RATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>buy_rate IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeRateEntry> fetchByBuyRate(BigDecimal... values) {
        return fetch(ExchangeRateEntry.EXCHANGE_RATE_ENTRY.BUY_RATE, values);
    }

    /**
     * Fetch records that have <code>middle_rate BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeRateEntry> fetchRangeOfMiddleRate(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(ExchangeRateEntry.EXCHANGE_RATE_ENTRY.MIDDLE_RATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>middle_rate IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeRateEntry> fetchByMiddleRate(BigDecimal... values) {
        return fetch(ExchangeRateEntry.EXCHANGE_RATE_ENTRY.MIDDLE_RATE, values);
    }

    /**
     * Fetch records that have <code>sell_rate BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeRateEntry> fetchRangeOfSellRate(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(ExchangeRateEntry.EXCHANGE_RATE_ENTRY.SELL_RATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>sell_rate IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeRateEntry> fetchBySellRate(BigDecimal... values) {
        return fetch(ExchangeRateEntry.EXCHANGE_RATE_ENTRY.SELL_RATE, values);
    }

    /**
     * Fetch records that have <code>timestamp_of_creating BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeRateEntry> fetchRangeOfTimestampOfCreating(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(ExchangeRateEntry.EXCHANGE_RATE_ENTRY.TIMESTAMP_OF_CREATING, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>timestamp_of_creating IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeRateEntry> fetchByTimestampOfCreating(OffsetDateTime... values) {
        return fetch(ExchangeRateEntry.EXCHANGE_RATE_ENTRY.TIMESTAMP_OF_CREATING, values);
    }
}
