/*
 * This file is generated by jOOQ.
 */
package PlatniPrometDB.tables.daos;


import PlatniPrometDB.tables.ExchangeJob;
import PlatniPrometDB.tables.records.ExchangeJobRecord;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExchangeJobDao extends DAOImpl<ExchangeJobRecord, PlatniPrometDB.tables.pojos.ExchangeJob, Long> {

    /**
     * Create a new ExchangeJobDao without any configuration
     */
    public ExchangeJobDao() {
        super(ExchangeJob.EXCHANGE_JOB, PlatniPrometDB.tables.pojos.ExchangeJob.class);
    }

    /**
     * Create a new ExchangeJobDao with an attached configuration
     */
    public ExchangeJobDao(Configuration configuration) {
        super(ExchangeJob.EXCHANGE_JOB, PlatniPrometDB.tables.pojos.ExchangeJob.class, configuration);
    }

    @Override
    public Long getId(PlatniPrometDB.tables.pojos.ExchangeJob object) {
        return object.getExchangeJobId();
    }

    /**
     * Fetch records that have <code>exchange_job_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeJob> fetchRangeOfExchangeJobId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ExchangeJob.EXCHANGE_JOB.EXCHANGE_JOB_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>exchange_job_id IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeJob> fetchByExchangeJobId(Long... values) {
        return fetch(ExchangeJob.EXCHANGE_JOB.EXCHANGE_JOB_ID, values);
    }

    /**
     * Fetch a unique record that has <code>exchange_job_id = value</code>
     */
    public PlatniPrometDB.tables.pojos.ExchangeJob fetchOneByExchangeJobId(Long value) {
        return fetchOne(ExchangeJob.EXCHANGE_JOB.EXCHANGE_JOB_ID, value);
    }

    /**
     * Fetch a unique record that has <code>exchange_job_id = value</code>
     */
    public Optional<PlatniPrometDB.tables.pojos.ExchangeJob> fetchOptionalByExchangeJobId(Long value) {
        return fetchOptional(ExchangeJob.EXCHANGE_JOB.EXCHANGE_JOB_ID, value);
    }

    /**
     * Fetch records that have <code>job_type_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeJob> fetchRangeOfJobTypeId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ExchangeJob.EXCHANGE_JOB.JOB_TYPE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>job_type_id IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeJob> fetchByJobTypeId(Long... values) {
        return fetch(ExchangeJob.EXCHANGE_JOB.JOB_TYPE_ID, values);
    }

    /**
     * Fetch records that have <code>received_amount BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeJob> fetchRangeOfReceivedAmount(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(ExchangeJob.EXCHANGE_JOB.RECEIVED_AMOUNT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>received_amount IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeJob> fetchByReceivedAmount(BigDecimal... values) {
        return fetch(ExchangeJob.EXCHANGE_JOB.RECEIVED_AMOUNT, values);
    }

    /**
     * Fetch records that have <code>received_currency_code BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeJob> fetchRangeOfReceivedCurrencyCode(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ExchangeJob.EXCHANGE_JOB.RECEIVED_CURRENCY_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>received_currency_code IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeJob> fetchByReceivedCurrencyCode(Integer... values) {
        return fetch(ExchangeJob.EXCHANGE_JOB.RECEIVED_CURRENCY_CODE, values);
    }

    /**
     * Fetch records that have <code>exchange_rate_entry_id BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeJob> fetchRangeOfExchangeRateEntryId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ExchangeJob.EXCHANGE_JOB.EXCHANGE_RATE_ENTRY_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>exchange_rate_entry_id IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeJob> fetchByExchangeRateEntryId(Long... values) {
        return fetch(ExchangeJob.EXCHANGE_JOB.EXCHANGE_RATE_ENTRY_ID, values);
    }

    /**
     * Fetch records that have <code>middle_rate_amount BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeJob> fetchRangeOfMiddleRateAmount(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(ExchangeJob.EXCHANGE_JOB.MIDDLE_RATE_AMOUNT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>middle_rate_amount IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeJob> fetchByMiddleRateAmount(BigDecimal... values) {
        return fetch(ExchangeJob.EXCHANGE_JOB.MIDDLE_RATE_AMOUNT, values);
    }

    /**
     * Fetch records that have <code>exchange_amount BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeJob> fetchRangeOfExchangeAmount(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(ExchangeJob.EXCHANGE_JOB.EXCHANGE_AMOUNT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>exchange_amount IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeJob> fetchByExchangeAmount(BigDecimal... values) {
        return fetch(ExchangeJob.EXCHANGE_JOB.EXCHANGE_AMOUNT, values);
    }

    /**
     * Fetch records that have <code>exchange_cash_denomination_id BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeJob> fetchRangeOfExchangeCashDenominationId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ExchangeJob.EXCHANGE_JOB.EXCHANGE_CASH_DENOMINATION_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>exchange_cash_denomination_id IN
     * (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeJob> fetchByExchangeCashDenominationId(Long... values) {
        return fetch(ExchangeJob.EXCHANGE_JOB.EXCHANGE_CASH_DENOMINATION_ID, values);
    }

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeJob> fetchRangeOfUserId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ExchangeJob.EXCHANGE_JOB.USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeJob> fetchByUserId(Long... values) {
        return fetch(ExchangeJob.EXCHANGE_JOB.USER_ID, values);
    }

    /**
     * Fetch records that have <code>timestamp_of_creation BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeJob> fetchRangeOfTimestampOfCreation(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(ExchangeJob.EXCHANGE_JOB.TIMESTAMP_OF_CREATION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>timestamp_of_creation IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeJob> fetchByTimestampOfCreation(OffsetDateTime... values) {
        return fetch(ExchangeJob.EXCHANGE_JOB.TIMESTAMP_OF_CREATION, values);
    }

    /**
     * Fetch records that have <code>date_of_creation BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeJob> fetchRangeOfDateOfCreation(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(ExchangeJob.EXCHANGE_JOB.DATE_OF_CREATION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>date_of_creation IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeJob> fetchByDateOfCreation(LocalDate... values) {
        return fetch(ExchangeJob.EXCHANGE_JOB.DATE_OF_CREATION, values);
    }

    /**
     * Fetch records that have <code>time_of_creation BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeJob> fetchRangeOfTimeOfCreation(LocalTime lowerInclusive, LocalTime upperInclusive) {
        return fetchRange(ExchangeJob.EXCHANGE_JOB.TIME_OF_CREATION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>time_of_creation IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeJob> fetchByTimeOfCreation(LocalTime... values) {
        return fetch(ExchangeJob.EXCHANGE_JOB.TIME_OF_CREATION, values);
    }
}
