/*
 * This file is generated by jOOQ.
 */
package PlatniPrometDB.tables.daos;


import PlatniPrometDB.tables.ExchangeRate;
import PlatniPrometDB.tables.records.ExchangeRateRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExchangeRateDao extends DAOImpl<ExchangeRateRecord, PlatniPrometDB.tables.pojos.ExchangeRate, Long> {

    /**
     * Create a new ExchangeRateDao without any configuration
     */
    public ExchangeRateDao() {
        super(ExchangeRate.EXCHANGE_RATE, PlatniPrometDB.tables.pojos.ExchangeRate.class);
    }

    /**
     * Create a new ExchangeRateDao with an attached configuration
     */
    public ExchangeRateDao(Configuration configuration) {
        super(ExchangeRate.EXCHANGE_RATE, PlatniPrometDB.tables.pojos.ExchangeRate.class, configuration);
    }

    @Override
    public Long getId(PlatniPrometDB.tables.pojos.ExchangeRate object) {
        return object.getExchangeRateId();
    }

    /**
     * Fetch records that have <code>exchange_rate_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeRate> fetchRangeOfExchangeRateId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ExchangeRate.EXCHANGE_RATE.EXCHANGE_RATE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>exchange_rate_id IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeRate> fetchByExchangeRateId(Long... values) {
        return fetch(ExchangeRate.EXCHANGE_RATE.EXCHANGE_RATE_ID, values);
    }

    /**
     * Fetch a unique record that has <code>exchange_rate_id = value</code>
     */
    public PlatniPrometDB.tables.pojos.ExchangeRate fetchOneByExchangeRateId(Long value) {
        return fetchOne(ExchangeRate.EXCHANGE_RATE.EXCHANGE_RATE_ID, value);
    }

    /**
     * Fetch a unique record that has <code>exchange_rate_id = value</code>
     */
    public Optional<PlatniPrometDB.tables.pojos.ExchangeRate> fetchOptionalByExchangeRateId(Long value) {
        return fetchOptional(ExchangeRate.EXCHANGE_RATE.EXCHANGE_RATE_ID, value);
    }

    /**
     * Fetch records that have <code>timestamp_of_start BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeRate> fetchRangeOfTimestampOfStart(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(ExchangeRate.EXCHANGE_RATE.TIMESTAMP_OF_START, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>timestamp_of_start IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeRate> fetchByTimestampOfStart(LocalDate... values) {
        return fetch(ExchangeRate.EXCHANGE_RATE.TIMESTAMP_OF_START, values);
    }

    /**
     * Fetch records that have <code>timestamp_of_end BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeRate> fetchRangeOfTimestampOfEnd(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(ExchangeRate.EXCHANGE_RATE.TIMESTAMP_OF_END, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>timestamp_of_end IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeRate> fetchByTimestampOfEnd(LocalDate... values) {
        return fetch(ExchangeRate.EXCHANGE_RATE.TIMESTAMP_OF_END, values);
    }

    /**
     * Fetch records that have <code>fl_active BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeRate> fetchRangeOfFlActive(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(ExchangeRate.EXCHANGE_RATE.FL_ACTIVE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>fl_active IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeRate> fetchByFlActive(Boolean... values) {
        return fetch(ExchangeRate.EXCHANGE_RATE.FL_ACTIVE, values);
    }

    /**
     * Fetch records that have <code>created_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeRate> fetchRangeOfCreatedBy(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ExchangeRate.EXCHANGE_RATE.CREATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeRate> fetchByCreatedBy(Long... values) {
        return fetch(ExchangeRate.EXCHANGE_RATE.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>timestamp_of_creation BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeRate> fetchRangeOfTimestampOfCreation(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ExchangeRate.EXCHANGE_RATE.TIMESTAMP_OF_CREATION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>timestamp_of_creation IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeRate> fetchByTimestampOfCreation(LocalDateTime... values) {
        return fetch(ExchangeRate.EXCHANGE_RATE.TIMESTAMP_OF_CREATION, values);
    }

    /**
     * Fetch records that have <code>changed_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeRate> fetchRangeOfChangedBy(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ExchangeRate.EXCHANGE_RATE.CHANGED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>changed_by IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeRate> fetchByChangedBy(Long... values) {
        return fetch(ExchangeRate.EXCHANGE_RATE.CHANGED_BY, values);
    }

    /**
     * Fetch records that have <code>timestamp_of_change BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeRate> fetchRangeOfTimestampOfChange(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ExchangeRate.EXCHANGE_RATE.TIMESTAMP_OF_CHANGE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>timestamp_of_change IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.ExchangeRate> fetchByTimestampOfChange(LocalDateTime... values) {
        return fetch(ExchangeRate.EXCHANGE_RATE.TIMESTAMP_OF_CHANGE, values);
    }
}
