/*
 * This file is generated by jOOQ.
 */
package PlatniPrometDB.tables.daos;


import PlatniPrometDB.tables.JobType;
import PlatniPrometDB.tables.records.JobTypeRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobTypeDao extends DAOImpl<JobTypeRecord, PlatniPrometDB.tables.pojos.JobType, Long> {

    /**
     * Create a new JobTypeDao without any configuration
     */
    public JobTypeDao() {
        super(JobType.JOB_TYPE, PlatniPrometDB.tables.pojos.JobType.class);
    }

    /**
     * Create a new JobTypeDao with an attached configuration
     */
    public JobTypeDao(Configuration configuration) {
        super(JobType.JOB_TYPE, PlatniPrometDB.tables.pojos.JobType.class, configuration);
    }

    @Override
    public Long getId(PlatniPrometDB.tables.pojos.JobType object) {
        return object.getJobTypeId();
    }

    /**
     * Fetch records that have <code>job_type_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.JobType> fetchRangeOfJobTypeId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(JobType.JOB_TYPE.JOB_TYPE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>job_type_id IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.JobType> fetchByJobTypeId(Long... values) {
        return fetch(JobType.JOB_TYPE.JOB_TYPE_ID, values);
    }

    /**
     * Fetch a unique record that has <code>job_type_id = value</code>
     */
    public PlatniPrometDB.tables.pojos.JobType fetchOneByJobTypeId(Long value) {
        return fetchOne(JobType.JOB_TYPE.JOB_TYPE_ID, value);
    }

    /**
     * Fetch a unique record that has <code>job_type_id = value</code>
     */
    public Optional<PlatniPrometDB.tables.pojos.JobType> fetchOptionalByJobTypeId(Long value) {
        return fetchOptional(JobType.JOB_TYPE.JOB_TYPE_ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.JobType> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(JobType.JOB_TYPE.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.JobType> fetchByName(String... values) {
        return fetch(JobType.JOB_TYPE.NAME, values);
    }

    /**
     * Fetch records that have <code>description BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.JobType> fetchRangeOfDescription(String lowerInclusive, String upperInclusive) {
        return fetchRange(JobType.JOB_TYPE.DESCRIPTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.JobType> fetchByDescription(String... values) {
        return fetch(JobType.JOB_TYPE.DESCRIPTION, values);
    }
}
