/*
 * This file is generated by jOOQ.
 */
package PlatniPrometDB.tables.daos;


import PlatniPrometDB.tables.User;
import PlatniPrometDB.tables.records.UserRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDao extends DAOImpl<UserRecord, PlatniPrometDB.tables.pojos.User, Long> {

    /**
     * Create a new UserDao without any configuration
     */
    public UserDao() {
        super(User.USER, PlatniPrometDB.tables.pojos.User.class);
    }

    /**
     * Create a new UserDao with an attached configuration
     */
    public UserDao(Configuration configuration) {
        super(User.USER, PlatniPrometDB.tables.pojos.User.class, configuration);
    }

    @Override
    public Long getId(PlatniPrometDB.tables.pojos.User object) {
        return object.getUserId();
    }

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.User> fetchRangeOfUserId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(User.USER.USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.User> fetchByUserId(Long... values) {
        return fetch(User.USER.USER_ID, values);
    }

    /**
     * Fetch a unique record that has <code>user_id = value</code>
     */
    public PlatniPrometDB.tables.pojos.User fetchOneByUserId(Long value) {
        return fetchOne(User.USER.USER_ID, value);
    }

    /**
     * Fetch a unique record that has <code>user_id = value</code>
     */
    public Optional<PlatniPrometDB.tables.pojos.User> fetchOptionalByUserId(Long value) {
        return fetchOptional(User.USER.USER_ID, value);
    }

    /**
     * Fetch records that have <code>username BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.User> fetchRangeOfUsername(String lowerInclusive, String upperInclusive) {
        return fetchRange(User.USER.USERNAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.User> fetchByUsername(String... values) {
        return fetch(User.USER.USERNAME, values);
    }

    /**
     * Fetch records that have <code>role_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.User> fetchRangeOfRoleId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(User.USER.ROLE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>role_id IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.User> fetchByRoleId(Integer... values) {
        return fetch(User.USER.ROLE_ID, values);
    }

    /**
     * Fetch records that have <code>fl_active BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.User> fetchRangeOfFlActive(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(User.USER.FL_ACTIVE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>fl_active IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.User> fetchByFlActive(Boolean... values) {
        return fetch(User.USER.FL_ACTIVE, values);
    }

    /**
     * Fetch records that have <code>date_of_start BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.User> fetchRangeOfDateOfStart(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(User.USER.DATE_OF_START, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>date_of_start IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.User> fetchByDateOfStart(LocalDate... values) {
        return fetch(User.USER.DATE_OF_START, values);
    }

    /**
     * Fetch records that have <code>date_of_end BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.User> fetchRangeOfDateOfEnd(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(User.USER.DATE_OF_END, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>date_of_end IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.User> fetchByDateOfEnd(LocalDate... values) {
        return fetch(User.USER.DATE_OF_END, values);
    }

    /**
     * Fetch records that have <code>timestamp_of_creation BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.User> fetchRangeOfTimestampOfCreation(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(User.USER.TIMESTAMP_OF_CREATION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>timestamp_of_creation IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.User> fetchByTimestampOfCreation(LocalDateTime... values) {
        return fetch(User.USER.TIMESTAMP_OF_CREATION, values);
    }
}
