/*
 * This file is generated by jOOQ.
 */
package PlatniPrometDB.tables.daos;


import PlatniPrometDB.tables.UserPersonalInfo;
import PlatniPrometDB.tables.records.UserPersonalInfoRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserPersonalInfoDao extends DAOImpl<UserPersonalInfoRecord, PlatniPrometDB.tables.pojos.UserPersonalInfo, Long> {

    /**
     * Create a new UserPersonalInfoDao without any configuration
     */
    public UserPersonalInfoDao() {
        super(UserPersonalInfo.USER_PERSONAL_INFO, PlatniPrometDB.tables.pojos.UserPersonalInfo.class);
    }

    /**
     * Create a new UserPersonalInfoDao with an attached configuration
     */
    public UserPersonalInfoDao(Configuration configuration) {
        super(UserPersonalInfo.USER_PERSONAL_INFO, PlatniPrometDB.tables.pojos.UserPersonalInfo.class, configuration);
    }

    @Override
    public Long getId(PlatniPrometDB.tables.pojos.UserPersonalInfo object) {
        return object.getUserId();
    }

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.UserPersonalInfo> fetchRangeOfUserId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(UserPersonalInfo.USER_PERSONAL_INFO.USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.UserPersonalInfo> fetchByUserId(Long... values) {
        return fetch(UserPersonalInfo.USER_PERSONAL_INFO.USER_ID, values);
    }

    /**
     * Fetch a unique record that has <code>user_id = value</code>
     */
    public PlatniPrometDB.tables.pojos.UserPersonalInfo fetchOneByUserId(Long value) {
        return fetchOne(UserPersonalInfo.USER_PERSONAL_INFO.USER_ID, value);
    }

    /**
     * Fetch a unique record that has <code>user_id = value</code>
     */
    public Optional<PlatniPrometDB.tables.pojos.UserPersonalInfo> fetchOptionalByUserId(Long value) {
        return fetchOptional(UserPersonalInfo.USER_PERSONAL_INFO.USER_ID, value);
    }

    /**
     * Fetch records that have <code>first_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.UserPersonalInfo> fetchRangeOfFirstName(String lowerInclusive, String upperInclusive) {
        return fetchRange(UserPersonalInfo.USER_PERSONAL_INFO.FIRST_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>first_name IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.UserPersonalInfo> fetchByFirstName(String... values) {
        return fetch(UserPersonalInfo.USER_PERSONAL_INFO.FIRST_NAME, values);
    }

    /**
     * Fetch records that have <code>last_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.UserPersonalInfo> fetchRangeOfLastName(String lowerInclusive, String upperInclusive) {
        return fetchRange(UserPersonalInfo.USER_PERSONAL_INFO.LAST_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_name IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.UserPersonalInfo> fetchByLastName(String... values) {
        return fetch(UserPersonalInfo.USER_PERSONAL_INFO.LAST_NAME, values);
    }

    /**
     * Fetch records that have <code>date_of_birth BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.UserPersonalInfo> fetchRangeOfDateOfBirth(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(UserPersonalInfo.USER_PERSONAL_INFO.DATE_OF_BIRTH, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>date_of_birth IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.UserPersonalInfo> fetchByDateOfBirth(LocalDate... values) {
        return fetch(UserPersonalInfo.USER_PERSONAL_INFO.DATE_OF_BIRTH, values);
    }

    /**
     * Fetch records that have <code>phone_number BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.UserPersonalInfo> fetchRangeOfPhoneNumber(String lowerInclusive, String upperInclusive) {
        return fetchRange(UserPersonalInfo.USER_PERSONAL_INFO.PHONE_NUMBER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>phone_number IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.UserPersonalInfo> fetchByPhoneNumber(String... values) {
        return fetch(UserPersonalInfo.USER_PERSONAL_INFO.PHONE_NUMBER, values);
    }

    /**
     * Fetch records that have <code>address BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.UserPersonalInfo> fetchRangeOfAddress(String lowerInclusive, String upperInclusive) {
        return fetchRange(UserPersonalInfo.USER_PERSONAL_INFO.ADDRESS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>address IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.UserPersonalInfo> fetchByAddress(String... values) {
        return fetch(UserPersonalInfo.USER_PERSONAL_INFO.ADDRESS, values);
    }

    /**
     * Fetch records that have <code>city BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.UserPersonalInfo> fetchRangeOfCity(String lowerInclusive, String upperInclusive) {
        return fetchRange(UserPersonalInfo.USER_PERSONAL_INFO.CITY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>city IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.UserPersonalInfo> fetchByCity(String... values) {
        return fetch(UserPersonalInfo.USER_PERSONAL_INFO.CITY, values);
    }

    /**
     * Fetch records that have <code>timestamp_of_creation BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<PlatniPrometDB.tables.pojos.UserPersonalInfo> fetchRangeOfTimestampOfCreation(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(UserPersonalInfo.USER_PERSONAL_INFO.TIMESTAMP_OF_CREATION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>timestamp_of_creation IN (values)</code>
     */
    public List<PlatniPrometDB.tables.pojos.UserPersonalInfo> fetchByTimestampOfCreation(LocalDateTime... values) {
        return fetch(UserPersonalInfo.USER_PERSONAL_INFO.TIMESTAMP_OF_CREATION, values);
    }
}
