/*
 * This file is generated by jOOQ.
 */
package PlatniPrometDB.tables.records;


import PlatniPrometDB.tables.CashRegister;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CashRegisterRecord extends UpdatableRecordImpl<CashRegisterRecord> implements Record6<Long, String, Boolean, OffsetDateTime, Boolean, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.cash_register.cash_register_id</code>.
     */
    public void setCashRegisterId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.cash_register.cash_register_id</code>.
     */
    public Long getCashRegisterId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.cash_register.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.cash_register.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.cash_register.fl_active</code>.
     */
    public void setFlActive(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.cash_register.fl_active</code>.
     */
    public Boolean getFlActive() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.cash_register.timestamp_of_creation</code>.
     */
    public void setTimestampOfCreation(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.cash_register.timestamp_of_creation</code>.
     */
    public OffsetDateTime getTimestampOfCreation() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.cash_register.fl_in_use</code>.
     */
    public void setFlInUse(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.cash_register.fl_in_use</code>.
     */
    public Boolean getFlInUse() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.cash_register.fl_treasury</code>.
     */
    public void setFlTreasury(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.cash_register.fl_treasury</code>.
     */
    public Boolean getFlTreasury() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, Boolean, OffsetDateTime, Boolean, Boolean> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, Boolean, OffsetDateTime, Boolean, Boolean> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return CashRegister.CASH_REGISTER.CASH_REGISTER_ID;
    }

    @Override
    public Field<String> field2() {
        return CashRegister.CASH_REGISTER.NAME;
    }

    @Override
    public Field<Boolean> field3() {
        return CashRegister.CASH_REGISTER.FL_ACTIVE;
    }

    @Override
    public Field<OffsetDateTime> field4() {
        return CashRegister.CASH_REGISTER.TIMESTAMP_OF_CREATION;
    }

    @Override
    public Field<Boolean> field5() {
        return CashRegister.CASH_REGISTER.FL_IN_USE;
    }

    @Override
    public Field<Boolean> field6() {
        return CashRegister.CASH_REGISTER.FL_TREASURY;
    }

    @Override
    public Long component1() {
        return getCashRegisterId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Boolean component3() {
        return getFlActive();
    }

    @Override
    public OffsetDateTime component4() {
        return getTimestampOfCreation();
    }

    @Override
    public Boolean component5() {
        return getFlInUse();
    }

    @Override
    public Boolean component6() {
        return getFlTreasury();
    }

    @Override
    public Long value1() {
        return getCashRegisterId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Boolean value3() {
        return getFlActive();
    }

    @Override
    public OffsetDateTime value4() {
        return getTimestampOfCreation();
    }

    @Override
    public Boolean value5() {
        return getFlInUse();
    }

    @Override
    public Boolean value6() {
        return getFlTreasury();
    }

    @Override
    public CashRegisterRecord value1(Long value) {
        setCashRegisterId(value);
        return this;
    }

    @Override
    public CashRegisterRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public CashRegisterRecord value3(Boolean value) {
        setFlActive(value);
        return this;
    }

    @Override
    public CashRegisterRecord value4(OffsetDateTime value) {
        setTimestampOfCreation(value);
        return this;
    }

    @Override
    public CashRegisterRecord value5(Boolean value) {
        setFlInUse(value);
        return this;
    }

    @Override
    public CashRegisterRecord value6(Boolean value) {
        setFlTreasury(value);
        return this;
    }

    @Override
    public CashRegisterRecord values(Long value1, String value2, Boolean value3, OffsetDateTime value4, Boolean value5, Boolean value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CashRegisterRecord
     */
    public CashRegisterRecord() {
        super(CashRegister.CASH_REGISTER);
    }

    /**
     * Create a detached, initialised CashRegisterRecord
     */
    public CashRegisterRecord(Long cashRegisterId, String name, Boolean flActive, OffsetDateTime timestampOfCreation, Boolean flInUse, Boolean flTreasury) {
        super(CashRegister.CASH_REGISTER);

        setCashRegisterId(cashRegisterId);
        setName(name);
        setFlActive(flActive);
        setTimestampOfCreation(timestampOfCreation);
        setFlInUse(flInUse);
        setFlTreasury(flTreasury);
    }

    /**
     * Create a detached, initialised CashRegisterRecord
     */
    public CashRegisterRecord(PlatniPrometDB.tables.pojos.CashRegister value) {
        super(CashRegister.CASH_REGISTER);

        if (value != null) {
            setCashRegisterId(value.getCashRegisterId());
            setName(value.getName());
            setFlActive(value.getFlActive());
            setTimestampOfCreation(value.getTimestampOfCreation());
            setFlInUse(value.getFlInUse());
            setFlTreasury(value.getFlTreasury());
        }
    }
}
