/*
 * This file is generated by jOOQ.
 */
package PlatniPrometDB.tables.records;


import PlatniPrometDB.tables.Currency;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CurrencyRecord extends UpdatableRecordImpl<CurrencyRecord> implements Record6<String, String, String, Integer, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.currency.currency_code</code>.
     */
    public void setCurrencyCode(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.currency.currency_code</code>.
     */
    public String getCurrencyCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.currency.currency_name_code</code>.
     */
    public void setCurrencyNameCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.currency.currency_name_code</code>.
     */
    public String getCurrencyNameCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.currency.full_name</code>.
     */
    public void setFullName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.currency.full_name</code>.
     */
    public String getFullName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.currency.quantity</code>.
     */
    public void setQuantity(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.currency.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.currency.country</code>.
     */
    public void setCountry(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.currency.country</code>.
     */
    public String getCountry() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.currency.sign_logo</code>.
     */
    public void setSignLogo(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.currency.sign_logo</code>.
     */
    public String getSignLogo() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, String, String, Integer, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<String, String, String, Integer, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Currency.CURRENCY.CURRENCY_CODE;
    }

    @Override
    public Field<String> field2() {
        return Currency.CURRENCY.CURRENCY_NAME_CODE;
    }

    @Override
    public Field<String> field3() {
        return Currency.CURRENCY.FULL_NAME;
    }

    @Override
    public Field<Integer> field4() {
        return Currency.CURRENCY.QUANTITY;
    }

    @Override
    public Field<String> field5() {
        return Currency.CURRENCY.COUNTRY;
    }

    @Override
    public Field<String> field6() {
        return Currency.CURRENCY.SIGN_LOGO;
    }

    @Override
    public String component1() {
        return getCurrencyCode();
    }

    @Override
    public String component2() {
        return getCurrencyNameCode();
    }

    @Override
    public String component3() {
        return getFullName();
    }

    @Override
    public Integer component4() {
        return getQuantity();
    }

    @Override
    public String component5() {
        return getCountry();
    }

    @Override
    public String component6() {
        return getSignLogo();
    }

    @Override
    public String value1() {
        return getCurrencyCode();
    }

    @Override
    public String value2() {
        return getCurrencyNameCode();
    }

    @Override
    public String value3() {
        return getFullName();
    }

    @Override
    public Integer value4() {
        return getQuantity();
    }

    @Override
    public String value5() {
        return getCountry();
    }

    @Override
    public String value6() {
        return getSignLogo();
    }

    @Override
    public CurrencyRecord value1(String value) {
        setCurrencyCode(value);
        return this;
    }

    @Override
    public CurrencyRecord value2(String value) {
        setCurrencyNameCode(value);
        return this;
    }

    @Override
    public CurrencyRecord value3(String value) {
        setFullName(value);
        return this;
    }

    @Override
    public CurrencyRecord value4(Integer value) {
        setQuantity(value);
        return this;
    }

    @Override
    public CurrencyRecord value5(String value) {
        setCountry(value);
        return this;
    }

    @Override
    public CurrencyRecord value6(String value) {
        setSignLogo(value);
        return this;
    }

    @Override
    public CurrencyRecord values(String value1, String value2, String value3, Integer value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CurrencyRecord
     */
    public CurrencyRecord() {
        super(Currency.CURRENCY);
    }

    /**
     * Create a detached, initialised CurrencyRecord
     */
    public CurrencyRecord(String currencyCode, String currencyNameCode, String fullName, Integer quantity, String country, String signLogo) {
        super(Currency.CURRENCY);

        setCurrencyCode(currencyCode);
        setCurrencyNameCode(currencyNameCode);
        setFullName(fullName);
        setQuantity(quantity);
        setCountry(country);
        setSignLogo(signLogo);
    }

    /**
     * Create a detached, initialised CurrencyRecord
     */
    public CurrencyRecord(PlatniPrometDB.tables.pojos.Currency value) {
        super(Currency.CURRENCY);

        if (value != null) {
            setCurrencyCode(value.getCurrencyCode());
            setCurrencyNameCode(value.getCurrencyNameCode());
            setFullName(value.getFullName());
            setQuantity(value.getQuantity());
            setCountry(value.getCountry());
            setSignLogo(value.getSignLogo());
        }
    }
}
