/*
 * This file is generated by jOOQ.
 */
package PlatniPrometDB.tables.records;


import PlatniPrometDB.tables.ExchangeRateEntry;

import java.math.BigDecimal;
import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExchangeRateEntryRecord extends UpdatableRecordImpl<ExchangeRateEntryRecord> implements Record8<Long, Long, String, String, BigDecimal, BigDecimal, BigDecimal, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public.exchange_rate_entry.exchange_rate_entry_id</code>.
     */
    public void setExchangeRateEntryId(Long value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>public.exchange_rate_entry.exchange_rate_entry_id</code>.
     */
    public Long getExchangeRateEntryId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.exchange_rate_entry.exchange_rate_id</code>.
     */
    public void setExchangeRateId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.exchange_rate_entry.exchange_rate_id</code>.
     */
    public Long getExchangeRateId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.exchange_rate_entry.currency_code</code>.
     */
    public void setCurrencyCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.exchange_rate_entry.currency_code</code>.
     */
    public String getCurrencyCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.exchange_rate_entry.currency_name_code</code>.
     */
    public void setCurrencyNameCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.exchange_rate_entry.currency_name_code</code>.
     */
    public String getCurrencyNameCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.exchange_rate_entry.buy_rate</code>.
     */
    public void setBuyRate(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.exchange_rate_entry.buy_rate</code>.
     */
    public BigDecimal getBuyRate() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>public.exchange_rate_entry.middle_rate</code>.
     */
    public void setMiddleRate(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.exchange_rate_entry.middle_rate</code>.
     */
    public BigDecimal getMiddleRate() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>public.exchange_rate_entry.sell_rate</code>.
     */
    public void setSellRate(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.exchange_rate_entry.sell_rate</code>.
     */
    public BigDecimal getSellRate() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>public.exchange_rate_entry.timestamp_of_creating</code>.
     */
    public void setTimestampOfCreating(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.exchange_rate_entry.timestamp_of_creating</code>.
     */
    public OffsetDateTime getTimestampOfCreating() {
        return (OffsetDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, Long, String, String, BigDecimal, BigDecimal, BigDecimal, OffsetDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, Long, String, String, BigDecimal, BigDecimal, BigDecimal, OffsetDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ExchangeRateEntry.EXCHANGE_RATE_ENTRY.EXCHANGE_RATE_ENTRY_ID;
    }

    @Override
    public Field<Long> field2() {
        return ExchangeRateEntry.EXCHANGE_RATE_ENTRY.EXCHANGE_RATE_ID;
    }

    @Override
    public Field<String> field3() {
        return ExchangeRateEntry.EXCHANGE_RATE_ENTRY.CURRENCY_CODE;
    }

    @Override
    public Field<String> field4() {
        return ExchangeRateEntry.EXCHANGE_RATE_ENTRY.CURRENCY_NAME_CODE;
    }

    @Override
    public Field<BigDecimal> field5() {
        return ExchangeRateEntry.EXCHANGE_RATE_ENTRY.BUY_RATE;
    }

    @Override
    public Field<BigDecimal> field6() {
        return ExchangeRateEntry.EXCHANGE_RATE_ENTRY.MIDDLE_RATE;
    }

    @Override
    public Field<BigDecimal> field7() {
        return ExchangeRateEntry.EXCHANGE_RATE_ENTRY.SELL_RATE;
    }

    @Override
    public Field<OffsetDateTime> field8() {
        return ExchangeRateEntry.EXCHANGE_RATE_ENTRY.TIMESTAMP_OF_CREATING;
    }

    @Override
    public Long component1() {
        return getExchangeRateEntryId();
    }

    @Override
    public Long component2() {
        return getExchangeRateId();
    }

    @Override
    public String component3() {
        return getCurrencyCode();
    }

    @Override
    public String component4() {
        return getCurrencyNameCode();
    }

    @Override
    public BigDecimal component5() {
        return getBuyRate();
    }

    @Override
    public BigDecimal component6() {
        return getMiddleRate();
    }

    @Override
    public BigDecimal component7() {
        return getSellRate();
    }

    @Override
    public OffsetDateTime component8() {
        return getTimestampOfCreating();
    }

    @Override
    public Long value1() {
        return getExchangeRateEntryId();
    }

    @Override
    public Long value2() {
        return getExchangeRateId();
    }

    @Override
    public String value3() {
        return getCurrencyCode();
    }

    @Override
    public String value4() {
        return getCurrencyNameCode();
    }

    @Override
    public BigDecimal value5() {
        return getBuyRate();
    }

    @Override
    public BigDecimal value6() {
        return getMiddleRate();
    }

    @Override
    public BigDecimal value7() {
        return getSellRate();
    }

    @Override
    public OffsetDateTime value8() {
        return getTimestampOfCreating();
    }

    @Override
    public ExchangeRateEntryRecord value1(Long value) {
        setExchangeRateEntryId(value);
        return this;
    }

    @Override
    public ExchangeRateEntryRecord value2(Long value) {
        setExchangeRateId(value);
        return this;
    }

    @Override
    public ExchangeRateEntryRecord value3(String value) {
        setCurrencyCode(value);
        return this;
    }

    @Override
    public ExchangeRateEntryRecord value4(String value) {
        setCurrencyNameCode(value);
        return this;
    }

    @Override
    public ExchangeRateEntryRecord value5(BigDecimal value) {
        setBuyRate(value);
        return this;
    }

    @Override
    public ExchangeRateEntryRecord value6(BigDecimal value) {
        setMiddleRate(value);
        return this;
    }

    @Override
    public ExchangeRateEntryRecord value7(BigDecimal value) {
        setSellRate(value);
        return this;
    }

    @Override
    public ExchangeRateEntryRecord value8(OffsetDateTime value) {
        setTimestampOfCreating(value);
        return this;
    }

    @Override
    public ExchangeRateEntryRecord values(Long value1, Long value2, String value3, String value4, BigDecimal value5, BigDecimal value6, BigDecimal value7, OffsetDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExchangeRateEntryRecord
     */
    public ExchangeRateEntryRecord() {
        super(ExchangeRateEntry.EXCHANGE_RATE_ENTRY);
    }

    /**
     * Create a detached, initialised ExchangeRateEntryRecord
     */
    public ExchangeRateEntryRecord(Long exchangeRateEntryId, Long exchangeRateId, String currencyCode, String currencyNameCode, BigDecimal buyRate, BigDecimal middleRate, BigDecimal sellRate, OffsetDateTime timestampOfCreating) {
        super(ExchangeRateEntry.EXCHANGE_RATE_ENTRY);

        setExchangeRateEntryId(exchangeRateEntryId);
        setExchangeRateId(exchangeRateId);
        setCurrencyCode(currencyCode);
        setCurrencyNameCode(currencyNameCode);
        setBuyRate(buyRate);
        setMiddleRate(middleRate);
        setSellRate(sellRate);
        setTimestampOfCreating(timestampOfCreating);
    }

    /**
     * Create a detached, initialised ExchangeRateEntryRecord
     */
    public ExchangeRateEntryRecord(PlatniPrometDB.tables.pojos.ExchangeRateEntry value) {
        super(ExchangeRateEntry.EXCHANGE_RATE_ENTRY);

        if (value != null) {
            setExchangeRateEntryId(value.getExchangeRateEntryId());
            setExchangeRateId(value.getExchangeRateId());
            setCurrencyCode(value.getCurrencyCode());
            setCurrencyNameCode(value.getCurrencyNameCode());
            setBuyRate(value.getBuyRate());
            setMiddleRate(value.getMiddleRate());
            setSellRate(value.getSellRate());
            setTimestampOfCreating(value.getTimestampOfCreating());
        }
    }
}
