/*
 * This file is generated by jOOQ.
 */
package PlatniPrometDB.tables.records;


import PlatniPrometDB.tables.Organisation;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrganisationRecord extends UpdatableRecordImpl<OrganisationRecord> implements Record7<Long, String, String, String, String, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.organisation.organisation_id</code>.
     */
    public void setOrganisationId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.organisation.organisation_id</code>.
     */
    public Long getOrganisationId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.organisation.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.organisation.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.organisation.legal_id</code>.
     */
    public void setLegalId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.organisation.legal_id</code>.
     */
    public String getLegalId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.organisation.address</code>.
     */
    public void setAddress(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.organisation.address</code>.
     */
    public String getAddress() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.organisation.city</code>.
     */
    public void setCity(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.organisation.city</code>.
     */
    public String getCity() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.organisation.phone_number</code>.
     */
    public void setPhoneNumber(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.organisation.phone_number</code>.
     */
    public String getPhoneNumber() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.organisation.timestamp_of_creation</code>.
     */
    public void setTimestampOfCreation(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.organisation.timestamp_of_creation</code>.
     */
    public LocalDateTime getTimestampOfCreation() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, String, String, String, String, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, String, String, String, String, String, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Organisation.ORGANISATION.ORGANISATION_ID;
    }

    @Override
    public Field<String> field2() {
        return Organisation.ORGANISATION.NAME;
    }

    @Override
    public Field<String> field3() {
        return Organisation.ORGANISATION.LEGAL_ID;
    }

    @Override
    public Field<String> field4() {
        return Organisation.ORGANISATION.ADDRESS;
    }

    @Override
    public Field<String> field5() {
        return Organisation.ORGANISATION.CITY;
    }

    @Override
    public Field<String> field6() {
        return Organisation.ORGANISATION.PHONE_NUMBER;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Organisation.ORGANISATION.TIMESTAMP_OF_CREATION;
    }

    @Override
    public Long component1() {
        return getOrganisationId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getLegalId();
    }

    @Override
    public String component4() {
        return getAddress();
    }

    @Override
    public String component5() {
        return getCity();
    }

    @Override
    public String component6() {
        return getPhoneNumber();
    }

    @Override
    public LocalDateTime component7() {
        return getTimestampOfCreation();
    }

    @Override
    public Long value1() {
        return getOrganisationId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getLegalId();
    }

    @Override
    public String value4() {
        return getAddress();
    }

    @Override
    public String value5() {
        return getCity();
    }

    @Override
    public String value6() {
        return getPhoneNumber();
    }

    @Override
    public LocalDateTime value7() {
        return getTimestampOfCreation();
    }

    @Override
    public OrganisationRecord value1(Long value) {
        setOrganisationId(value);
        return this;
    }

    @Override
    public OrganisationRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public OrganisationRecord value3(String value) {
        setLegalId(value);
        return this;
    }

    @Override
    public OrganisationRecord value4(String value) {
        setAddress(value);
        return this;
    }

    @Override
    public OrganisationRecord value5(String value) {
        setCity(value);
        return this;
    }

    @Override
    public OrganisationRecord value6(String value) {
        setPhoneNumber(value);
        return this;
    }

    @Override
    public OrganisationRecord value7(LocalDateTime value) {
        setTimestampOfCreation(value);
        return this;
    }

    @Override
    public OrganisationRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrganisationRecord
     */
    public OrganisationRecord() {
        super(Organisation.ORGANISATION);
    }

    /**
     * Create a detached, initialised OrganisationRecord
     */
    public OrganisationRecord(Long organisationId, String name, String legalId, String address, String city, String phoneNumber, LocalDateTime timestampOfCreation) {
        super(Organisation.ORGANISATION);

        setOrganisationId(organisationId);
        setName(name);
        setLegalId(legalId);
        setAddress(address);
        setCity(city);
        setPhoneNumber(phoneNumber);
        setTimestampOfCreation(timestampOfCreation);
    }

    /**
     * Create a detached, initialised OrganisationRecord
     */
    public OrganisationRecord(PlatniPrometDB.tables.pojos.Organisation value) {
        super(Organisation.ORGANISATION);

        if (value != null) {
            setOrganisationId(value.getOrganisationId());
            setName(value.getName());
            setLegalId(value.getLegalId());
            setAddress(value.getAddress());
            setCity(value.getCity());
            setPhoneNumber(value.getPhoneNumber());
            setTimestampOfCreation(value.getTimestampOfCreation());
        }
    }
}
