/*
 * This file is generated by jOOQ.
 */
package PlatniPrometDB.tables.records;


import PlatniPrometDB.tables.UserPersonalInfo;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserPersonalInfoRecord extends UpdatableRecordImpl<UserPersonalInfoRecord> implements Record8<Long, String, String, LocalDate, String, String, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_personal_info.user_id</code>.
     */
    public void setUserId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_personal_info.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.user_personal_info.first_name</code>.
     */
    public void setFirstName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_personal_info.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.user_personal_info.last_name</code>.
     */
    public void setLastName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_personal_info.last_name</code>.
     */
    public String getLastName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.user_personal_info.date_of_birth</code>.
     */
    public void setDateOfBirth(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.user_personal_info.date_of_birth</code>.
     */
    public LocalDate getDateOfBirth() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>public.user_personal_info.phone_number</code>.
     */
    public void setPhoneNumber(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.user_personal_info.phone_number</code>.
     */
    public String getPhoneNumber() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.user_personal_info.address</code>.
     */
    public void setAddress(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.user_personal_info.address</code>.
     */
    public String getAddress() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.user_personal_info.city</code>.
     */
    public void setCity(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.user_personal_info.city</code>.
     */
    public String getCity() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.user_personal_info.timestamp_of_creation</code>.
     */
    public void setTimestampOfCreation(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.user_personal_info.timestamp_of_creation</code>.
     */
    public LocalDateTime getTimestampOfCreation() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, String, String, LocalDate, String, String, String, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, String, String, LocalDate, String, String, String, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UserPersonalInfo.USER_PERSONAL_INFO.USER_ID;
    }

    @Override
    public Field<String> field2() {
        return UserPersonalInfo.USER_PERSONAL_INFO.FIRST_NAME;
    }

    @Override
    public Field<String> field3() {
        return UserPersonalInfo.USER_PERSONAL_INFO.LAST_NAME;
    }

    @Override
    public Field<LocalDate> field4() {
        return UserPersonalInfo.USER_PERSONAL_INFO.DATE_OF_BIRTH;
    }

    @Override
    public Field<String> field5() {
        return UserPersonalInfo.USER_PERSONAL_INFO.PHONE_NUMBER;
    }

    @Override
    public Field<String> field6() {
        return UserPersonalInfo.USER_PERSONAL_INFO.ADDRESS;
    }

    @Override
    public Field<String> field7() {
        return UserPersonalInfo.USER_PERSONAL_INFO.CITY;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return UserPersonalInfo.USER_PERSONAL_INFO.TIMESTAMP_OF_CREATION;
    }

    @Override
    public Long component1() {
        return getUserId();
    }

    @Override
    public String component2() {
        return getFirstName();
    }

    @Override
    public String component3() {
        return getLastName();
    }

    @Override
    public LocalDate component4() {
        return getDateOfBirth();
    }

    @Override
    public String component5() {
        return getPhoneNumber();
    }

    @Override
    public String component6() {
        return getAddress();
    }

    @Override
    public String component7() {
        return getCity();
    }

    @Override
    public LocalDateTime component8() {
        return getTimestampOfCreation();
    }

    @Override
    public Long value1() {
        return getUserId();
    }

    @Override
    public String value2() {
        return getFirstName();
    }

    @Override
    public String value3() {
        return getLastName();
    }

    @Override
    public LocalDate value4() {
        return getDateOfBirth();
    }

    @Override
    public String value5() {
        return getPhoneNumber();
    }

    @Override
    public String value6() {
        return getAddress();
    }

    @Override
    public String value7() {
        return getCity();
    }

    @Override
    public LocalDateTime value8() {
        return getTimestampOfCreation();
    }

    @Override
    public UserPersonalInfoRecord value1(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserPersonalInfoRecord value2(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public UserPersonalInfoRecord value3(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public UserPersonalInfoRecord value4(LocalDate value) {
        setDateOfBirth(value);
        return this;
    }

    @Override
    public UserPersonalInfoRecord value5(String value) {
        setPhoneNumber(value);
        return this;
    }

    @Override
    public UserPersonalInfoRecord value6(String value) {
        setAddress(value);
        return this;
    }

    @Override
    public UserPersonalInfoRecord value7(String value) {
        setCity(value);
        return this;
    }

    @Override
    public UserPersonalInfoRecord value8(LocalDateTime value) {
        setTimestampOfCreation(value);
        return this;
    }

    @Override
    public UserPersonalInfoRecord values(Long value1, String value2, String value3, LocalDate value4, String value5, String value6, String value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserPersonalInfoRecord
     */
    public UserPersonalInfoRecord() {
        super(UserPersonalInfo.USER_PERSONAL_INFO);
    }

    /**
     * Create a detached, initialised UserPersonalInfoRecord
     */
    public UserPersonalInfoRecord(Long userId, String firstName, String lastName, LocalDate dateOfBirth, String phoneNumber, String address, String city, LocalDateTime timestampOfCreation) {
        super(UserPersonalInfo.USER_PERSONAL_INFO);

        setUserId(userId);
        setFirstName(firstName);
        setLastName(lastName);
        setDateOfBirth(dateOfBirth);
        setPhoneNumber(phoneNumber);
        setAddress(address);
        setCity(city);
        setTimestampOfCreation(timestampOfCreation);
    }

    /**
     * Create a detached, initialised UserPersonalInfoRecord
     */
    public UserPersonalInfoRecord(PlatniPrometDB.tables.pojos.UserPersonalInfo value) {
        super(UserPersonalInfo.USER_PERSONAL_INFO);

        if (value != null) {
            setUserId(value.getUserId());
            setFirstName(value.getFirstName());
            setLastName(value.getLastName());
            setDateOfBirth(value.getDateOfBirth());
            setPhoneNumber(value.getPhoneNumber());
            setAddress(value.getAddress());
            setCity(value.getCity());
            setTimestampOfCreation(value.getTimestampOfCreation());
        }
    }
}
