/*
 * This file is generated by jOOQ.
 */
package PlatniPrometDB.tables.records;


import PlatniPrometDB.tables.User;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record7<Long, String, Integer, Boolean, LocalDate, LocalDate, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user.user_id</code>.
     */
    public void setUserId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.user.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.user.role_id</code>.
     */
    public void setRoleId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user.role_id</code>.
     */
    public Integer getRoleId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.user.fl_active</code>.
     */
    public void setFlActive(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.user.fl_active</code>.
     */
    public Boolean getFlActive() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.user.date_of_start</code>.
     */
    public void setDateOfStart(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.user.date_of_start</code>.
     */
    public LocalDate getDateOfStart() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for <code>public.user.date_of_end</code>.
     */
    public void setDateOfEnd(LocalDate value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.user.date_of_end</code>.
     */
    public LocalDate getDateOfEnd() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>public.user.timestamp_of_creation</code>.
     */
    public void setTimestampOfCreation(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.user.timestamp_of_creation</code>.
     */
    public LocalDateTime getTimestampOfCreation() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, Integer, Boolean, LocalDate, LocalDate, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, String, Integer, Boolean, LocalDate, LocalDate, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return User.USER.USER_ID;
    }

    @Override
    public Field<String> field2() {
        return User.USER.USERNAME;
    }

    @Override
    public Field<Integer> field3() {
        return User.USER.ROLE_ID;
    }

    @Override
    public Field<Boolean> field4() {
        return User.USER.FL_ACTIVE;
    }

    @Override
    public Field<LocalDate> field5() {
        return User.USER.DATE_OF_START;
    }

    @Override
    public Field<LocalDate> field6() {
        return User.USER.DATE_OF_END;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return User.USER.TIMESTAMP_OF_CREATION;
    }

    @Override
    public Long component1() {
        return getUserId();
    }

    @Override
    public String component2() {
        return getUsername();
    }

    @Override
    public Integer component3() {
        return getRoleId();
    }

    @Override
    public Boolean component4() {
        return getFlActive();
    }

    @Override
    public LocalDate component5() {
        return getDateOfStart();
    }

    @Override
    public LocalDate component6() {
        return getDateOfEnd();
    }

    @Override
    public LocalDateTime component7() {
        return getTimestampOfCreation();
    }

    @Override
    public Long value1() {
        return getUserId();
    }

    @Override
    public String value2() {
        return getUsername();
    }

    @Override
    public Integer value3() {
        return getRoleId();
    }

    @Override
    public Boolean value4() {
        return getFlActive();
    }

    @Override
    public LocalDate value5() {
        return getDateOfStart();
    }

    @Override
    public LocalDate value6() {
        return getDateOfEnd();
    }

    @Override
    public LocalDateTime value7() {
        return getTimestampOfCreation();
    }

    @Override
    public UserRecord value1(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserRecord value2(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public UserRecord value3(Integer value) {
        setRoleId(value);
        return this;
    }

    @Override
    public UserRecord value4(Boolean value) {
        setFlActive(value);
        return this;
    }

    @Override
    public UserRecord value5(LocalDate value) {
        setDateOfStart(value);
        return this;
    }

    @Override
    public UserRecord value6(LocalDate value) {
        setDateOfEnd(value);
        return this;
    }

    @Override
    public UserRecord value7(LocalDateTime value) {
        setTimestampOfCreation(value);
        return this;
    }

    @Override
    public UserRecord values(Long value1, String value2, Integer value3, Boolean value4, LocalDate value5, LocalDate value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Long userId, String username, Integer roleId, Boolean flActive, LocalDate dateOfStart, LocalDate dateOfEnd, LocalDateTime timestampOfCreation) {
        super(User.USER);

        setUserId(userId);
        setUsername(username);
        setRoleId(roleId);
        setFlActive(flActive);
        setDateOfStart(dateOfStart);
        setDateOfEnd(dateOfEnd);
        setTimestampOfCreation(timestampOfCreation);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(PlatniPrometDB.tables.pojos.User value) {
        super(User.USER);

        if (value != null) {
            setUserId(value.getUserId());
            setUsername(value.getUsername());
            setRoleId(value.getRoleId());
            setFlActive(value.getFlActive());
            setDateOfStart(value.getDateOfStart());
            setDateOfEnd(value.getDateOfEnd());
            setTimestampOfCreation(value.getTimestampOfCreation());
        }
    }
}
