/*
 * This file is generated by jOOQ.
 */
package PlatniPrometDB.tables.records;


import PlatniPrometDB.tables.WorkPlace;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkPlaceRecord extends UpdatableRecordImpl<WorkPlaceRecord> implements Record6<Long, Long, Long, OffsetDateTime, OffsetDateTime, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.work_place.work_place_id</code>.
     */
    public void setWorkPlaceId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.work_place.work_place_id</code>.
     */
    public Long getWorkPlaceId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.work_place.cash_register_id</code>.
     */
    public void setCashRegisterId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.work_place.cash_register_id</code>.
     */
    public Long getCashRegisterId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.work_place.user_id</code>.
     */
    public void setUserId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.work_place.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.work_place.timestamp_of_open</code>.
     */
    public void setTimestampOfOpen(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.work_place.timestamp_of_open</code>.
     */
    public OffsetDateTime getTimestampOfOpen() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.work_place.timestamp_of_close</code>.
     */
    public void setTimestampOfClose(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.work_place.timestamp_of_close</code>.
     */
    public OffsetDateTime getTimestampOfClose() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.work_place.timestamp_of_creation</code>.
     */
    public void setTimestampOfCreation(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.work_place.timestamp_of_creation</code>.
     */
    public OffsetDateTime getTimestampOfCreation() {
        return (OffsetDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Long, OffsetDateTime, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, Long, OffsetDateTime, OffsetDateTime, OffsetDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return WorkPlace.WORK_PLACE.WORK_PLACE_ID;
    }

    @Override
    public Field<Long> field2() {
        return WorkPlace.WORK_PLACE.CASH_REGISTER_ID;
    }

    @Override
    public Field<Long> field3() {
        return WorkPlace.WORK_PLACE.USER_ID;
    }

    @Override
    public Field<OffsetDateTime> field4() {
        return WorkPlace.WORK_PLACE.TIMESTAMP_OF_OPEN;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return WorkPlace.WORK_PLACE.TIMESTAMP_OF_CLOSE;
    }

    @Override
    public Field<OffsetDateTime> field6() {
        return WorkPlace.WORK_PLACE.TIMESTAMP_OF_CREATION;
    }

    @Override
    public Long component1() {
        return getWorkPlaceId();
    }

    @Override
    public Long component2() {
        return getCashRegisterId();
    }

    @Override
    public Long component3() {
        return getUserId();
    }

    @Override
    public OffsetDateTime component4() {
        return getTimestampOfOpen();
    }

    @Override
    public OffsetDateTime component5() {
        return getTimestampOfClose();
    }

    @Override
    public OffsetDateTime component6() {
        return getTimestampOfCreation();
    }

    @Override
    public Long value1() {
        return getWorkPlaceId();
    }

    @Override
    public Long value2() {
        return getCashRegisterId();
    }

    @Override
    public Long value3() {
        return getUserId();
    }

    @Override
    public OffsetDateTime value4() {
        return getTimestampOfOpen();
    }

    @Override
    public OffsetDateTime value5() {
        return getTimestampOfClose();
    }

    @Override
    public OffsetDateTime value6() {
        return getTimestampOfCreation();
    }

    @Override
    public WorkPlaceRecord value1(Long value) {
        setWorkPlaceId(value);
        return this;
    }

    @Override
    public WorkPlaceRecord value2(Long value) {
        setCashRegisterId(value);
        return this;
    }

    @Override
    public WorkPlaceRecord value3(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public WorkPlaceRecord value4(OffsetDateTime value) {
        setTimestampOfOpen(value);
        return this;
    }

    @Override
    public WorkPlaceRecord value5(OffsetDateTime value) {
        setTimestampOfClose(value);
        return this;
    }

    @Override
    public WorkPlaceRecord value6(OffsetDateTime value) {
        setTimestampOfCreation(value);
        return this;
    }

    @Override
    public WorkPlaceRecord values(Long value1, Long value2, Long value3, OffsetDateTime value4, OffsetDateTime value5, OffsetDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorkPlaceRecord
     */
    public WorkPlaceRecord() {
        super(WorkPlace.WORK_PLACE);
    }

    /**
     * Create a detached, initialised WorkPlaceRecord
     */
    public WorkPlaceRecord(Long workPlaceId, Long cashRegisterId, Long userId, OffsetDateTime timestampOfOpen, OffsetDateTime timestampOfClose, OffsetDateTime timestampOfCreation) {
        super(WorkPlace.WORK_PLACE);

        setWorkPlaceId(workPlaceId);
        setCashRegisterId(cashRegisterId);
        setUserId(userId);
        setTimestampOfOpen(timestampOfOpen);
        setTimestampOfClose(timestampOfClose);
        setTimestampOfCreation(timestampOfCreation);
    }

    /**
     * Create a detached, initialised WorkPlaceRecord
     */
    public WorkPlaceRecord(PlatniPrometDB.tables.pojos.WorkPlace value) {
        super(WorkPlace.WORK_PLACE);

        if (value != null) {
            setWorkPlaceId(value.getWorkPlaceId());
            setCashRegisterId(value.getCashRegisterId());
            setUserId(value.getUserId());
            setTimestampOfOpen(value.getTimestampOfOpen());
            setTimestampOfClose(value.getTimestampOfClose());
            setTimestampOfCreation(value.getTimestampOfCreation());
        }
    }
}
