/*
 * This file is generated by jOOQ.
 */
package PlatniPrometDB;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.balance_entry_balance_entry_id_seq</code>
     */
    public static final Sequence<Long> BALANCE_ENTRY_BALANCE_ENTRY_ID_SEQ = Internal.createSequence("balance_entry_balance_entry_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.banknote_detail_seq</code>
     */
    public static final Sequence<Long> BANKNOTE_DETAIL_SEQ = Internal.createSequence("banknote_detail_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.cash_register_seq</code>
     */
    public static final Sequence<Long> CASH_REGISTER_SEQ = Internal.createSequence("cash_register_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.exchange_cash_denomination_seq</code>
     */
    public static final Sequence<Long> EXCHANGE_CASH_DENOMINATION_SEQ = Internal.createSequence("exchange_cash_denomination_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.exchange_job_seq</code>
     */
    public static final Sequence<Long> EXCHANGE_JOB_SEQ = Internal.createSequence("exchange_job_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.exchange_rate_entry_id_seq</code>
     */
    public static final Sequence<Long> EXCHANGE_RATE_ENTRY_ID_SEQ = Internal.createSequence("exchange_rate_entry_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.exchange_rate_id_seq</code>
     */
    public static final Sequence<Long> EXCHANGE_RATE_ID_SEQ = Internal.createSequence("exchange_rate_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.organisation_seq</code>
     */
    public static final Sequence<Long> ORGANISATION_SEQ = Internal.createSequence("organisation_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.user_seq</code>
     */
    public static final Sequence<Long> USER_SEQ = Internal.createSequence("user_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.work_place_seq</code>
     */
    public static final Sequence<Long> WORK_PLACE_SEQ = Internal.createSequence("work_place_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
