/*
 * This file is generated by jOOQ.
 */
package PlatniPrometDB;


import PlatniPrometDB.tables.BalanceEntry;
import PlatniPrometDB.tables.BanknoteDetail;
import PlatniPrometDB.tables.CashRegister;
import PlatniPrometDB.tables.Currency;
import PlatniPrometDB.tables.ExchangeCashDenomination;
import PlatniPrometDB.tables.ExchangeJob;
import PlatniPrometDB.tables.ExchangeRate;
import PlatniPrometDB.tables.ExchangeRateEntry;
import PlatniPrometDB.tables.JobType;
import PlatniPrometDB.tables.Organisation;
import PlatniPrometDB.tables.Role;
import PlatniPrometDB.tables.User;
import PlatniPrometDB.tables.UserAuth;
import PlatniPrometDB.tables.UserPersonalInfo;
import PlatniPrometDB.tables.WorkPlace;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.balance_entry</code>.
     */
    public static final BalanceEntry BALANCE_ENTRY = BalanceEntry.BALANCE_ENTRY;

    /**
     * The table <code>public.banknote_detail</code>.
     */
    public static final BanknoteDetail BANKNOTE_DETAIL = BanknoteDetail.BANKNOTE_DETAIL;

    /**
     * The table <code>public.cash_register</code>.
     */
    public static final CashRegister CASH_REGISTER = CashRegister.CASH_REGISTER;

    /**
     * The table <code>public.currency</code>.
     */
    public static final Currency CURRENCY = Currency.CURRENCY;

    /**
     * The table <code>public.exchange_cash_denomination</code>.
     */
    public static final ExchangeCashDenomination EXCHANGE_CASH_DENOMINATION = ExchangeCashDenomination.EXCHANGE_CASH_DENOMINATION;

    /**
     * The table <code>public.exchange_job</code>.
     */
    public static final ExchangeJob EXCHANGE_JOB = ExchangeJob.EXCHANGE_JOB;

    /**
     * The table <code>public.exchange_rate</code>.
     */
    public static final ExchangeRate EXCHANGE_RATE = ExchangeRate.EXCHANGE_RATE;

    /**
     * The table <code>public.exchange_rate_entry</code>.
     */
    public static final ExchangeRateEntry EXCHANGE_RATE_ENTRY = ExchangeRateEntry.EXCHANGE_RATE_ENTRY;

    /**
     * The table <code>public.job_type</code>.
     */
    public static final JobType JOB_TYPE = JobType.JOB_TYPE;

    /**
     * The table <code>public.organisation</code>.
     */
    public static final Organisation ORGANISATION = Organisation.ORGANISATION;

    /**
     * The table <code>public.role</code>.
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>public.user_auth</code>.
     */
    public static final UserAuth USER_AUTH = UserAuth.USER_AUTH;

    /**
     * The table <code>public.user_personal_info</code>.
     */
    public static final UserPersonalInfo USER_PERSONAL_INFO = UserPersonalInfo.USER_PERSONAL_INFO;

    /**
     * The table <code>public.work_place</code>.
     */
    public static final WorkPlace WORK_PLACE = WorkPlace.WORK_PLACE;
}
